(function() {
  'use strict';

  // Ensure global bus is ready
  window.SpyGameCore = window.SpyGameCore || {
    state: {},
    services: {},
    offline: {},
    online: {},
    components: {}
  };

  /**
   * FILE 1: SpyGame-config.js
   * Responsibility: Initial state, constants, translations, and the complete word bank.
   */

  const GAME_CONFIG = {
    MIN_PLAYERS: 3,
    MAX_PLAYERS: 12,
    MAX_SPIES: 2,
    HOLD_REVEAL_MS: 1500,
    SPY_GUESS_SECONDS: 15,
    HEARTBEAT_INTERVAL_MS: 15000,
    HOST_TIMEOUT_MS: 30000,
    REVOTE_DURATION_S: 20,
    DEFAULT_TIMER: 300
  };

  const I18N = {
    en: {
      home_title: "Who is the Spy?",
      home_offline: "Play Together 🃏",
      home_online: "Play Online 🌐",
      setup_add_player: "Add player",
      lobby_ready: "Ready",
      lobby_not_ready: "Not Ready",
      lobby_start: "Start Game",
      lobby_kick: "Kick",
      distribute_pass: "Pass the phone to",
      distribute_hold: "Hold to reveal word",
      distribute_seen: "I've seen my word ✓",
      distribute_spy_badge: "🕵️ You are the Spy!",
      distribute_waiting: "Waiting for others...",
      discuss_done: "Done speaking",
      vote_lock: "Vote locked",
      vote_waiting: "Waiting for votes:",
      reveal_accused: "ACCUSED!",
      reveal_caught: "🕵️ SPY CAUGHT!",
      reveal_escaped: "✅ The Spy Escaped!",
      reveal_guess_prompt: "Guess the real word...",
      reveal_guess_submit: "Submit Guess",
      results_next: "Next Round",
      results_end: "End Game",
      final_play_again: "Play Again",
      final_new_game: "New Game",
      final_leave: "Leave",
      bonus_vote: "Most Convincing Clue +1",
      no_majority: "No Majority — Re-vote!",
      spy_escaped_tech: "Spy Escapes on Technicality",
      two_spies_toast: "2 Spies in this round! 🕵️🕵️",
      vote_failed: "Vote failed, try again",
      copied: "Copied!",
      room_not_found: "Room not found or expired",
      room_full: "Room is full",
      game_started: "Game already started",
      reconnecting: "Reconnecting...",
      host_left: "Host left — you are now the host"
    },
    ar: {
      home_title: "من هو الجاسوس؟",
      home_offline: "العب مع أصحابك 🃏",
      home_online: "العب أونلاين 🌐",
      setup_add_player: "أضف لاعب",
      lobby_ready: "جاهز",
      lobby_not_ready: "مش جاهز",
      lobby_start: "ابدأ اللعبة",
      lobby_kick: "طرد",
      distribute_pass: "مرر الهاتف لـ",
      distribute_hold: "اضغط لرؤية كلمتك",
      distribute_seen: "شفت كلمتي ✓",
      distribute_spy_badge: "🕵️ أنت الجاسوس!",
      distribute_waiting: "في انتظار البقية...",
      discuss_done: "انتهيت",
      vote_lock: "تم التصويت",
      vote_waiting: "في انتظار التصويت:",
      reveal_accused: "المتهم!",
      reveal_caught: "🕵️ تم كشف الجاسوس!",
      reveal_escaped: "✅ الجاسوس أفلت!",
      reveal_guess_prompt: "اكتب الكلمة الحقيقية...",
      reveal_guess_submit: "تأكيد",
      results_next: "الجولة التالية",
      results_end: "إنهاء اللعبة",
      final_play_again: "العب مجددًا",
      final_new_game: "لعبة جديدة",
      final_leave: "خروج",
      bonus_vote: "أفضل تلميح +1",
      no_majority: "تعادل — إعادة التصويت!",
      spy_escaped_tech: "الجاسوس أفلت بحيلة",
      two_spies_toast: "جاسوسان في هذه الجولة! 🕵️🕵️",
      vote_failed: "فشل التصويت، حاول مجددًا",
      copied: "تم النسخ!",
      room_not_found: "الغرفة غير موجودة أو منتهية",
      room_full: "الغرفة ممتلئة",
      game_started: "اللعبة بدأت بالفعل",
      reconnecting: "جاري الاتصال...",
      host_left: "المضيف غادر — أنت المضيف الآن"
    }
  };

  /**
   * WORD_BANK Implementation (Batch 1/3)
   * 600 words total across 15 categories.
   */
  const WORD_BANK = {
    animals: [
      { word_en: "Lion", word_ar: "أسد", emoji: "🦁", difficulty: "easy", decoy_en: "Tiger", decoy_ar: "نمر" },
      { word_en: "Elephant", word_ar: "فيل", emoji: "🐘", difficulty: "easy", decoy_en: "Hippo", decoy_ar: "فرس النهر" },
      { word_en: "Giraffe", word_ar: "زرافة", emoji: "🦒", difficulty: "easy", decoy_en: "Zebra", decoy_ar: "حمار وحشي" },
      { word_en: "Penguin", word_ar: "بطريق", emoji: "🐧", difficulty: "medium", decoy_en: "Seal", decoy_ar: "فقمة" },
      { word_en: "Kangaroo", word_ar: "كانغارو", emoji: "🦘", difficulty: "medium", decoy_en: "Koala", decoy_ar: "كوالا" },
      { word_en: "Octopus", word_ar: "أخطبوط", emoji: "🐙", difficulty: "medium", decoy_en: "Squid", decoy_ar: "حبار" },
      { word_en: "Butterfly", word_ar: "فراشة", emoji: "🦋", difficulty: "easy", decoy_en: "Moth", decoy_ar: "عثة" },
      { word_en: "Dolphin", word_ar: "دلفين", emoji: "🐬", difficulty: "easy", decoy_en: "Whale", decoy_ar: "حوت" },
      { word_en: "Eagle", word_ar: "نسر", emoji: "🦅", difficulty: "medium", decoy_en: "Hawk", decoy_ar: "صقر" },
      { word_en: "Shark", word_ar: "قرش", emoji: "🦈", difficulty: "easy", decoy_en: "Ray", decoy_ar: "سمك الشفنين" },
      { word_en: "Cheetah", word_ar: "فهد", emoji: "🐆", difficulty: "hard", decoy_en: "Leopard", decoy_ar: "نمر منقط" },
      { word_en: "Camel", word_ar: "جمل", emoji: "🐫", difficulty: "easy", decoy_en: "Llama", decoy_ar: "لاما" },
      { word_en: "Crocodile", word_ar: "تمساح", emoji: "🐊", difficulty: "medium", decoy_en: "Alligator", decoy_ar: "قاطور" },
      { word_en: "Owl", word_ar: "بومة", emoji: "🦉", difficulty: "medium", decoy_en: "Bat", decoy_ar: "خفاش" },
      { word_en: "Panda", word_ar: "باندا", emoji: "🐼", difficulty: "easy", decoy_en: "Koala", decoy_ar: "كوالا" },
      { word_en: "Wolf", word_ar: "ذئب", emoji: "🐺", difficulty: "medium", decoy_en: "Fox", decoy_ar: "ثعلب" },
      { word_en: "Peacock", word_ar: "طاووس", emoji: "🦚", difficulty: "medium", decoy_en: "Parrot", decoy_ar: "ببغاء" },
      { word_en: "Rhino", word_ar: "وحيد القرن", emoji: "🦏", difficulty: "hard", decoy_en: "Hippo", decoy_ar: "فرس النهر" },
      { word_en: "Sloth", word_ar: "كسلان", emoji: "🦥", difficulty: "hard", decoy_en: "Koala", decoy_ar: "كوالا" },
      { word_en: "Flamingo", word_ar: "نحام", emoji: "🦩", difficulty: "hard", decoy_en: "Stork", decoy_ar: "لقلق" },
      { word_en: "Turtle", word_ar: "سلحفاة", emoji: "🐢", difficulty: "easy", decoy_en: "Tortoise", decoy_ar: "سلحفاة برية" },
      { word_en: "Gorilla", word_ar: "غوريلا", emoji: "🦍", difficulty: "medium", decoy_en: "Chimpanzee", decoy_ar: "شيمبانزي" },
      { word_en: "Jellyfish", word_ar: "قنديل البحر", emoji: "🪼", difficulty: "hard", decoy_en: "Anemone", decoy_ar: "شقيقة النعمان" },
      { word_en: "Squirrel", word_ar: "سنجاب", emoji: "🐿️", difficulty: "medium", decoy_en: "Chipmunk", decoy_ar: "سنجاب مخطط" },
      { word_en: "Bee", word_ar: "نحلة", emoji: "🐝", difficulty: "easy", decoy_en: "Wasp", decoy_ar: "دبور" },
      { word_en: "Zebra", word_ar: "حمار وحشي", emoji: "🏁", difficulty: "easy", decoy_en: "Horse", decoy_ar: "حصان" },
      { word_en: "Bat", word_ar: "خفاش", emoji: "🦇", difficulty: "medium", decoy_en: "Bird", decoy_ar: "طائر" },
      { word_en: "Crab", word_ar: "سرطان", emoji: "🦀", difficulty: "easy", decoy_en: "Lobster", decoy_ar: "كركند" },
      { word_en: "Snail", word_ar: "حلزون", emoji: "🐌", difficulty: "easy", decoy_en: "Slug", decoy_ar: "بزاقة" },
      { word_en: "Swan", word_ar: "بجعة", emoji: "🦢", difficulty: "medium", decoy_en: "Goose", decoy_ar: "وزة" },
      { word_en: "Woodpecker", word_ar: "نقار الخشب", emoji: "🐦", difficulty: "hard", decoy_en: "Kingfisher", decoy_ar: "رفراف" },
      { word_en: "Platypus", word_ar: "خلد الماء", emoji: "🦆", difficulty: "hard", decoy_en: "Beaver", decoy_ar: "قندس" },
      { word_en: "Ant", word_ar: "نملة", emoji: "🐜", difficulty: "easy", decoy_en: "Termite", decoy_ar: "أرضة" },
      { word_en: "Octopus", word_ar: "أخطبوط", emoji: "🐙", difficulty: "medium", decoy_en: "Cuttlefish", decoy_ar: "حبّار" },
      { word_en: "Seahorse", word_ar: "فرس البحر", emoji: "🧜‍♂️", difficulty: "hard", decoy_en: "Shrimp", decoy_ar: "روبيان" },
      { word_en: "Ladybug", word_ar: "دعسوقة", emoji: "🐞", difficulty: "medium", decoy_en: "Beetle", decoy_ar: "خنفساء" },
      { word_en: "Mosquito", word_ar: "بعوضة", emoji: "🦟", difficulty: "easy", decoy_en: "Fly", decoy_ar: "ذبابة" },
      { word_en: "Ostrich", word_ar: "نعامة", emoji: "🐦", difficulty: "medium", decoy_en: "Emu", decoy_ar: "إيمو" },
      { word_en: "Spider", word_ar: "عنكبوت", emoji: "🕷️", difficulty: "easy", decoy_en: "Scorpion", decoy_ar: "عقرب" },
      { word_en: "Walrus", word_ar: "فيل البحر", emoji: "🦷", difficulty: "hard", decoy_en: "Seal", decoy_ar: "فقمة" }
    ],
    food: [
      { word_en: "Pizza", word_ar: "بيتزا", emoji: "🍕", difficulty: "easy", decoy_en: "Flatbread", decoy_ar: "خبز مفرود" },
      { word_en: "Sushi", word_ar: "سوشي", emoji: "🍣", difficulty: "easy", decoy_en: "Sashimi", decoy_ar: "ساشيمي" },
      { word_en: "Burger", word_ar: "برجر", emoji: "🍔", difficulty: "easy", decoy_en: "Sandwich", decoy_ar: "ساندوتش" },
      { word_en: "Pasta", word_ar: "باستا", emoji: "🍝", difficulty: "easy", decoy_en: "Noodles", decoy_ar: "نودلز" },
      { word_en: "Ice Cream", word_ar: "أيس كريم", emoji: "🍦", difficulty: "easy", decoy_en: "Yogurt", decoy_ar: "زبادي" },
      { word_en: "Taco", word_ar: "تاكو", emoji: "🌮", difficulty: "medium", decoy_en: "Burrito", decoy_ar: "بوريتو" },
      { word_en: "Steak", word_ar: "ستيك", emoji: "🥩", difficulty: "medium", decoy_en: "Ribs", decoy_ar: "أضلاع" },
      { word_en: "Pancakes", word_ar: "بانكيك", emoji: "🥞", difficulty: "medium", decoy_en: "Waffles", decoy_ar: "وافل" },
      { word_en: "Croissant", word_ar: "كرواسون", emoji: "🥐", difficulty: "medium", decoy_en: "Brioche", decoy_ar: "بريوش" },
      { word_en: "Donut", word_ar: "دونات", emoji: "🍩", difficulty: "easy", decoy_en: "Bagel", decoy_ar: "بيغل" },
      { word_en: "Salad", word_ar: "سلطة", emoji: "🥗", difficulty: "easy", decoy_en: "Coleslaw", decoy_ar: "كول سلو" },
      { word_en: "Ramen", word_ar: "رامن", emoji: "🍜", difficulty: "medium", decoy_en: "Pho", decoy_ar: "فو" },
      { word_en: "Cheese", word_ar: "جبن", emoji: "🧀", difficulty: "easy", decoy_en: "Butter", decoy_ar: "زبدة" },
      { word_en: "Chocolate", word_ar: "شوكولاتة", emoji: "🍫", difficulty: "easy", decoy_en: "Fudge", decoy_ar: "فدج" },
      { word_en: "Avocado", word_ar: "أفوكادو", emoji: "🥑", difficulty: "medium", decoy_en: "Guacamole", decoy_ar: "غواكامولي" },
      { word_en: "Popcorn", word_ar: "فشار", emoji: "🍿", difficulty: "easy", decoy_en: "Chips", decoy_ar: "شيبس" },
      { word_en: "Honey", word_ar: "عسل", emoji: "🍯", difficulty: "medium", decoy_en: "Syrup", decoy_ar: "شراب محلى" },
      { word_en: "Mushroom", word_ar: "فطر", emoji: "🍄", difficulty: "medium", decoy_en: "Truffle", decoy_ar: "كمأة" },
      { word_en: "Egg", word_ar: "بيض", emoji: "🥚", difficulty: "easy", decoy_en: "Tofu", decoy_ar: "توفو" },
      { word_en: "Garlic", word_ar: "ثوم", emoji: "🧄", difficulty: "medium", decoy_en: "Onion", decoy_ar: "بصل" },
      { word_en: "Cupcake", word_ar: "كب كيك", emoji: "🧁", difficulty: "easy", decoy_en: "Muffin", decoy_ar: "مافن" },
      { word_en: "Curry", word_ar: "كاري", emoji: "🍲", difficulty: "hard", decoy_en: "Stew", decoy_ar: "يخنة" },
      { word_en: "Pretzel", word_ar: "بريتزل", emoji: "🥨", difficulty: "hard", decoy_en: "Breadstick", decoy_ar: "أصابع خبز" },
      { word_en: "Sausage", word_ar: "سجق", emoji: "🌭", difficulty: "medium", decoy_en: "Bacon", decoy_ar: "لحم قديد" },
      { word_en: "Oyster", word_ar: "محار", emoji: "🦪", difficulty: "hard", decoy_en: "Clam", decoy_ar: "بلح البحر" },
      { word_en: "Watermelon", word_ar: "بطيخ", emoji: "🍉", difficulty: "easy", decoy_en: "Cantaloupe", decoy_ar: "شمام" },
      { word_en: "Shrimp", word_ar: "روبيان", emoji: "🦐", difficulty: "medium", decoy_en: "Prawn", decoy_ar: "جمبري" },
      { word_en: "Chili", word_ar: "فلفل حار", emoji: "🌶️", difficulty: "easy", decoy_en: "Bell Pepper", decoy_ar: "فلفل حلو" },
      { word_en: "Brownie", word_ar: "براوني", emoji: "🍰", difficulty: "medium", decoy_en: "Cake", decoy_ar: "كيك" },
      { word_en: "Lemon", word_ar: "ليمون", emoji: "🍋", difficulty: "easy", decoy_en: "Lime", decoy_ar: "ليمون حامض" },
      { word_en: "Bread", word_ar: "خبز", emoji: "🍞", difficulty: "easy", decoy_en: "Toast", decoy_ar: "توست" },
      { word_en: "Rice", word_ar: "أرز", emoji: "🍚", difficulty: "easy", decoy_en: "Grain", decoy_ar: "حبوب" },
      { word_en: "Soup", word_ar: "شوربة", emoji: "🥣", difficulty: "easy", decoy_en: "Broth", decoy_ar: "مرق" },
      { word_en: "Bacon", word_ar: "لحم قديد", emoji: "🥓", difficulty: "medium", decoy_en: "Ham", decoy_ar: "لانشون" },
      { word_en: "Cookie", word_ar: "بسكويت", emoji: "🍪", difficulty: "easy", decoy_en: "Biscuit", decoy_ar: "بسكويت" },
      { word_en: "Mango", word_ar: "مانجو", emoji: "🥭", difficulty: "medium", decoy_en: "Peach", decoy_ar: "خوخ" },
      { word_en: "Grapes", word_ar: "عنب", emoji: "🍇", difficulty: "easy", decoy_en: "Raisins", decoy_ar: "زبيب" },
      { word_en: "Olive", word_ar: "زيتون", emoji: "🫒", difficulty: "medium", decoy_en: "Caper", decoy_ar: "كبار" },
      { word_en: "Peanut", word_ar: "فول سوداني", emoji: "🥜", difficulty: "medium", decoy_en: "Almond", decoy_ar: "لوز" },
      { word_en: "Waffle", word_ar: "وافل", emoji: "🧇", difficulty: "medium", decoy_en: "Pancake", decoy_ar: "بانكيك" }
    ],
    sports: [
      { word_en: "Football", word_ar: "كرة قدم", emoji: "⚽", difficulty: "easy", decoy_en: "Rugby", decoy_ar: "رجبي" },
      { word_en: "Basketball", word_ar: "كرة سلة", emoji: "🏀", difficulty: "easy", decoy_en: "Netball", decoy_ar: "كرة شبكة" },
      { word_en: "Tennis", word_ar: "تنس", emoji: "🎾", difficulty: "easy", decoy_en: "Squash", decoy_ar: "سكواش" },
      { word_en: "Boxing", word_ar: "ملاكمة", emoji: "🥊", difficulty: "easy", decoy_en: "Kickboxing", decoy_ar: "كيك بوكسينغ" },
      { word_en: "Golf", word_ar: "جولف", emoji: "⛳", difficulty: "medium", decoy_en: "Cricket", decoy_ar: "كريكت" },
      { word_en: "Swimming", word_ar: "سباحة", emoji: "🏊", difficulty: "easy", decoy_en: "Diving", decoy_ar: "غطس" },
      { word_en: "Baseball", word_ar: "بيسبول", emoji: "⚾", difficulty: "medium", decoy_en: "Softball", decoy_ar: "سوفت بول" },
      { word_en: "Hockey", word_ar: "هوكي", emoji: "🏒", difficulty: "medium", decoy_en: "Lacrosse", decoy_ar: "لاكروس" },
      { word_en: "Skiing", word_ar: "تزلج", emoji: "🎿", difficulty: "medium", decoy_en: "Snowboarding", decoy_ar: "تزلج على الجليد" },
      { word_en: "Surfing", word_ar: "ركوب الأمواج", emoji: "🏄", difficulty: "medium", decoy_en: "Bodyboarding", decoy_ar: "بودي بوردنغ" },
      { word_en: "Bowling", word_ar: "بولينج", emoji: "🎳", difficulty: "easy", decoy_en: "Billiards", decoy_ar: "بلياردو" },
      { word_en: "Karate", word_ar: "كاراتيه", emoji: "🥋", difficulty: "medium", decoy_en: "Judo", decoy_ar: "جودو" },
      { word_en: "Running", word_ar: "جري", emoji: "🏃", difficulty: "easy", decoy_en: "Hiking", decoy_ar: "هايكنغ" },
      { word_en: "Cycling", word_ar: "ركوب الدراجات", emoji: "🚲", difficulty: "easy", decoy_en: "Motorcycling", decoy_ar: "ركوب الموتوسيكلات" },
      { word_en: "Yoga", word_ar: "يوغا", emoji: "🧘", difficulty: "medium", decoy_en: "Pilates", decoy_ar: "بيلاتس" },
      { word_en: "Archery", word_ar: "رماية بالسهام", emoji: "🏹", difficulty: "hard", decoy_en: "Shooting", decoy_ar: "رماية" },
      { word_en: "Chess", word_ar: "شطرنج", emoji: "♟️", difficulty: "medium", decoy_en: "Checkers", decoy_ar: "داما" },
      { word_en: "Volleyball", word_ar: "كرة طائرة", emoji: "🏐", difficulty: "easy", decoy_en: "Handball", decoy_ar: "كرة يد" },
      { word_en: "Fencing", word_ar: "مبارزة", emoji: "🤺", difficulty: "hard", decoy_en: "Swordplay", decoy_ar: "قتال سيوف" },
      { word_en: "Darts", word_ar: "سهام مريشة", emoji: "🎯", difficulty: "medium", decoy_en: "Billiards", decoy_ar: "بلياردو" },
      { word_en: "Wrestling", word_ar: "مصارعة", emoji: "🤼", difficulty: "medium", decoy_en: "Grappling", decoy_ar: "تشابك" },
      { word_en: "Gymnastics", word_ar: "جمباز", emoji: "🤸", difficulty: "hard", decoy_en: "Acrobatics", decoy_ar: "أكروبات" },
      { word_en: "Badminton", word_ar: "بادمنتون", emoji: "🏸", difficulty: "medium", decoy_en: "Tennis", decoy_ar: "تنس" },
      { word_en: "Rugby", word_ar: "رجبي", emoji: "🏉", difficulty: "medium", decoy_en: "Football", decoy_ar: "كرة قدم" },
      { word_en: "Cricket", word_ar: "كريكت", emoji: "🏏", difficulty: "hard", decoy_en: "Baseball", decoy_ar: "بيسبول" },
      { word_en: "Weightlifting", word_ar: "رفع أثقال", emoji: "🏋️", difficulty: "easy", decoy_en: "Powerlifting", decoy_ar: "باور ليفتنغ" },
      { word_en: "Biking", word_ar: "درجات", emoji: "🚵", difficulty: "easy", decoy_en: "Walking", decoy_ar: "مشى" },
      { word_en: "Skating", word_ar: "تزلج", emoji: "⛸️", difficulty: "medium", decoy_en: "Rollerblading", decoy_ar: "رولر بليدنغ" },
      { word_en: "Horse Racing", word_ar: "سباق خيل", emoji: "🐎", difficulty: "hard", decoy_en: "Polo", decoy_ar: "بولو" },
      { word_en: "Rowing", word_ar: "تجديف", emoji: "🚣", difficulty: "hard", decoy_en: "Canoeing", decoy_ar: "كانو" },
      { word_en: "Table Tennis", word_ar: "تنس طاولة", emoji: "🏓", difficulty: "easy", decoy_en: "Tennis", decoy_ar: "تنس" },
      { word_en: "Diving", word_ar: "غطس", emoji: "🤿", difficulty: "medium", decoy_en: "Snorkeling", decoy_ar: "سنوركلنغ" },
      { word_en: "Handball", word_ar: "كرة يد", emoji: "🤾", difficulty: "medium", decoy_en: "Water Polo", decoy_ar: "كرة مائية" },
      { word_en: "Squash", word_ar: "سكواش", emoji: "🎾", difficulty: "hard", decoy_en: "Racquetball", decoy_ar: "راكيت" },
      { word_en: "Climbing", word_ar: "تسلق", emoji: "🧗", difficulty: "hard", decoy_en: "Abseiling", decoy_ar: "نزول بالحبال" },
      { word_en: "Motorcycle", word_ar: "موتوسيكل", emoji: "🏍️", difficulty: "easy", decoy_en: "Scooter", decoy_ar: "سكوتر" },
      { word_en: "Skateboard", word_ar: "سكيت بورد", emoji: "🛹", difficulty: "medium", decoy_en: "Longboard", decoy_ar: "لونغ بورد" },
      { word_en: "Ping Pong", word_ar: "بينج بونج", emoji: "🏓", difficulty: "easy", decoy_en: "Tennis", decoy_ar: "تنس" },
      { word_en: "Lacrosse", word_ar: "لاكروس", emoji: "🥍", difficulty: "hard", decoy_en: "Field Hockey", decoy_ar: "هوكي ميدان" },
      { word_en: "Billiards", word_ar: "بلياردو", emoji: "🎱", difficulty: "medium", decoy_en: "Snooker", decoy_ar: "سنوكر" }
    ],
    countries: [
      { word_en: "Egypt", word_ar: "مصر", emoji: "🇪🇬", difficulty: "easy", decoy_en: "Jordan", decoy_ar: "الأردن" },
      { word_en: "Japan", word_ar: "اليابان", emoji: "🇯🇵", difficulty: "easy", decoy_en: "Korea", decoy_ar: "كوريا" },
      { word_en: "France", word_ar: "فرنسا", emoji: "🇫🇷", difficulty: "easy", decoy_en: "Italy", decoy_ar: "إيطاليا" },
      { word_en: "Brazil", word_ar: "البرازيل", emoji: "🇧🇷", difficulty: "easy", decoy_en: "Argentina", decoy_ar: "الأرجنتين" },
      { word_en: "Canada", word_ar: "كندا", emoji: "🇨🇦", difficulty: "easy", decoy_en: "USA", decoy_ar: "أمريكا" },
      { word_en: "Germany", word_ar: "ألمانيا", emoji: "🇩🇪", difficulty: "medium", decoy_en: "Austria", decoy_ar: "النمسا" },
      { word_en: "Australia", word_ar: "أستراليا", emoji: "🇦🇺", difficulty: "medium", decoy_en: "New Zealand", decoy_ar: "نيوزيلندا" },
      { word_en: "China", word_ar: "الصين", emoji: "🇨🇳", difficulty: "easy", decoy_en: "Vietnam", decoy_ar: "فيتنام" },
      { word_en: "India", word_ar: "الهند", emoji: "🇮🇳", difficulty: "easy", decoy_en: "Pakistan", decoy_ar: "باكستان" },
      { word_en: "Spain", word_ar: "إسبانيا", emoji: "🇪🇸", difficulty: "medium", decoy_en: "Portugal", decoy_ar: "البرتغال" },
      { word_en: "Mexico", word_ar: "المكسيك", emoji: "🇲🇽", difficulty: "easy", decoy_en: "Colombia", decoy_ar: "كولومبيا" },
      { word_en: "Russia", word_ar: "روسيا", emoji: "🇷🇺", difficulty: "medium", decoy_en: "Ukraine", decoy_ar: "أوكرانيا" },
      { word_en: "Italy", word_ar: "إيطاليا", emoji: "🇮🇹", difficulty: "easy", decoy_en: "Greece", decoy_ar: "اليونان" },
      { word_en: "UK", word_ar: "بريطانيا", emoji: "🇬🇧", difficulty: "easy", decoy_en: "Ireland", decoy_ar: "أيرلندا" },
      { word_en: "Saudi Arabia", word_ar: "السعودية", emoji: "🇸🇦", difficulty: "easy", decoy_en: "UAE", decoy_ar: "الإمارات" },
      { word_en: "Turkey", word_ar: "تركيا", emoji: "🇹🇷", difficulty: "medium", decoy_en: "Iran", decoy_ar: "إيران" },
      { word_en: "Greece", word_ar: "اليونان", emoji: "🇬🇷", difficulty: "hard", decoy_en: "Cyprus", decoy_ar: "قبرص" },
      { word_en: "Switzerland", word_ar: "سويسرا", emoji: "🇨🇭", difficulty: "hard", decoy_en: "Liechtenstein", decoy_ar: "ليختنشتاين" },
      { word_en: "South Korea", word_ar: "كوريا الجنوبية", emoji: "🇰🇷", difficulty: "medium", decoy_en: "North Korea", decoy_ar: "كوريا الشمالية" },
      { word_en: "Thailand", word_ar: "تايلاند", emoji: "🇹🇭", difficulty: "medium", decoy_en: "Malaysia", decoy_ar: "ماليزيا" },
      { word_en: "Netherlands", word_ar: "هولندا", emoji: "🇳🇱", difficulty: "hard", decoy_en: "Belgium", decoy_ar: "بلجيكا" },
      { word_en: "Norway", word_ar: "النرويج", emoji: "🇳🇴", difficulty: "hard", decoy_en: "Sweden", decoy_ar: "السويد" },
      { word_en: "Sweden", word_ar: "السويد", emoji: "🇸🇪", difficulty: "hard", decoy_en: "Denmark", decoy_ar: "الدنمارك" },
      { word_en: "Morocco", word_ar: "المغرب", emoji: "🇲🇦", difficulty: "easy", decoy_en: "Tunisia", decoy_ar: "تونس" },
      { word_en: "Colombia", word_ar: "كولومبيا", emoji: "🇨🇴", difficulty: "medium", decoy_en: "Peru", decoy_ar: "بيرو" },
      { word_en: "Vietnam", word_ar: "فيتنام", emoji: "🇻🇳", difficulty: "hard", decoy_en: "Laos", decoy_ar: "لاوس" },
      { word_en: "Poland", word_ar: "بولندا", emoji: "🇵🇱", difficulty: "hard", decoy_en: "Czechia", decoy_ar: "التشيك" },
      { word_en: "Argentina", word_ar: "الأرجنتين", emoji: "🇦🇷", difficulty: "medium", decoy_en: "Uruguay", decoy_ar: "أوروغواي" },
      { word_en: "UAE", word_ar: "الإمارات", emoji: "🇦🇪", difficulty: "easy", decoy_en: "Qatar", decoy_ar: "قطر" },
      { word_en: "Portugal", word_ar: "البرتغال", emoji: "🇵🇹", difficulty: "hard", decoy_en: "Spain", decoy_ar: "إسبانيا" },
      { word_en: "Kenya", word_ar: "كينيا", emoji: "🇰🇪", difficulty: "hard", decoy_en: "Tanzania", decoy_ar: "تنزانيا" },
      { word_en: "Nigeria", word_ar: "نيجيريا", emoji: "🇳🇬", difficulty: "hard", decoy_en: "Ghana", decoy_ar: "غانا" },
      { word_en: "Iceland", word_ar: "آيسلندا", emoji: "🇮🇸", difficulty: "hard", decoy_en: "Greenland", decoy_ar: "جرينلاند" },
      { word_en: "New Zealand", word_ar: "نيوزيلندا", emoji: "🇳🇿", difficulty: "hard", decoy_en: "Australia", decoy_ar: "أستراليا" },
      { word_en: "Finland", word_ar: "فنلندا", emoji: "🇫🇮", difficulty: "hard", decoy_en: "Estonia", decoy_ar: "إستونيا" },
      { word_en: "Belgium", word_ar: "بلجيكا", emoji: "🇧🇪", difficulty: "hard", decoy_en: "Netherlands", decoy_ar: "هولندا" },
      { word_en: "Philippines", word_ar: "الفلبين", emoji: "🇵🇭", difficulty: "medium", decoy_en: "Indonesia", decoy_ar: "إندونيسيا" },
      { word_en: "Singapore", word_ar: "سنغافورة", emoji: "🇸🇬", difficulty: "hard", decoy_en: "Hong Kong", decoy_ar: "هونغ كونغ" },
      { word_en: "Palestine", word_ar: "فلسطين", emoji: "🇵🇸", difficulty: "easy", decoy_en: "Jordan", decoy_ar: "الأردن" },
      { word_en: "Kuwait", word_ar: "الكويت", emoji: "🇰🇼", difficulty: "easy", decoy_en: "Bahrain", decoy_ar: "البحرين" }
    ],
    professions: [
      { word_en: "Doctor", word_ar: "طبيب", emoji: "👨‍⚕️", difficulty: "easy", decoy_en: "Nurse", decoy_ar: "ممرض" },
      { word_en: "Teacher", word_ar: "معلم", emoji: "👨‍🏫", difficulty: "easy", decoy_en: "Professor", decoy_ar: "بروفيسور" },
      { word_en: "Pilot", word_ar: "طيار", emoji: "👨‍✈️", difficulty: "easy", decoy_en: "Astronaut", decoy_ar: "رائد فضاء" },
      { word_en: "Chef", word_ar: "طاهي", emoji: "👨‍🍳", difficulty: "easy", decoy_en: "Baker", decoy_ar: "خباز" },
      { word_en: "Artist", word_ar: "فنان", emoji: "🎨", difficulty: "easy", decoy_en: "Designer", decoy_ar: "مصمم" },
      { word_en: "Engineer", word_ar: "مهندس", emoji: "👷", difficulty: "medium", decoy_en: "Architect", decoy_ar: "معماري" },
      { word_en: "Police Officer", word_ar: "شرطي", emoji: "👮", difficulty: "easy", decoy_en: "Detective", decoy_ar: "مخبر" },
      { word_en: "Firefighter", word_ar: "رجل إطفاء", emoji: "👨‍🚒", difficulty: "easy", decoy_en: "Officer", decoy_ar: "ضابط" },
      { word_en: "Photographer", word_ar: "مصور", emoji: "📷", difficulty: "medium", decoy_en: "Videographer", decoy_ar: "مصور فيديو" },
      { word_en: "Farmer", word_ar: "فلاح", emoji: "👨‍🌾", difficulty: "easy", decoy_en: "Gardener", decoy_ar: "بستاني" },
      { word_en: "Dancer", word_ar: "راقص", emoji: "💃", difficulty: "medium", decoy_en: "Gymnast", decoy_ar: "لاعب جمباز" },
      { word_en: "Scientist", word_ar: "عالم", emoji: "🧪", difficulty: "medium", decoy_en: "Researcher", decoy_ar: "باحث" },
      { word_en: "Lawyer", word_ar: "محامي", emoji: "⚖️", difficulty: "medium", decoy_en: "Judge", decoy_ar: "قاضي" },
      { word_en: "Musician", word_ar: "موسيقي", emoji: "🎸", difficulty: "easy", decoy_en: "Composer", decoy_ar: "ملحن" },
      { word_en: "Actor", word_ar: "ممثل", emoji: "🎭", difficulty: "easy", decoy_en: "Director", decoy_ar: "مخرج" },
      { word_en: "Journalist", word_ar: "صحفي", emoji: "📰", difficulty: "hard", decoy_en: "Writer", decoy_ar: "كاتب" },
      { word_en: "Programmer", word_ar: "مبرمج", emoji: "💻", difficulty: "medium", decoy_en: "Hacker", decoy_ar: "هاكر" },
      { word_en: "Soldier", word_ar: "جندي", emoji: "🪖", difficulty: "easy", decoy_en: "Marine", decoy_ar: "مارينز" },
      { word_en: "Astronaut", word_ar: "رائد فضاء", emoji: "👩‍🚀", difficulty: "hard", decoy_en: "Pilot", decoy_ar: "طيار" },
      { word_en: "Plumber", word_ar: "سباك", emoji: "👨‍🔧", difficulty: "medium", decoy_en: "Electrician", decoy_ar: "كهربائي" },
      { word_en: "Barber", word_ar: "حلاق", emoji: "💈", difficulty: "easy", decoy_en: "Stylist", decoy_ar: "مصفف شعر" },
      { word_en: "Carpenter", word_ar: "نجار", emoji: "🪚", difficulty: "medium", decoy_en: "Mason", decoy_ar: "بناء" },
      { word_en: "Athlete", word_ar: "رياضي", emoji: "🏅", difficulty: "easy", decoy_en: "Runner", decoy_ar: "عداء" },
      { word_en: "Librarian", word_ar: "أمين مكتبة", emoji: "📚", difficulty: "hard", decoy_en: "Archivist", decoy_ar: "موثق" },
      { word_en: "Sailor", word_ar: "بحار", emoji: "⛵", difficulty: "medium", decoy_en: "Captain", decoy_ar: "قبطان" },
      { word_en: "Waiter", word_ar: "نادل", emoji: "🤵", difficulty: "easy", decoy_en: "Host", decoy_ar: "مستضيف" },
      { word_en: "Mechanic", word_ar: "ميكانيكي", emoji: "👨‍🔧", difficulty: "medium", decoy_en: "Technician", decoy_ar: "فني" },
      { word_en: "Dentist", word_ar: "طبيب أسنان", emoji: "🦷", difficulty: "easy", decoy_en: "Orthodontist", decoy_ar: "طبيب تقويم" },
      { word_en: "Baker", word_ar: "خباز", emoji: "🥖", difficulty: "easy", decoy_en: "Pastry Chef", decoy_ar: "شيف حلويات" },
      { word_en: "Tailor", word_ar: "خياط", emoji: "🪡", difficulty: "medium", decoy_en: "Designer", decoy_ar: "مصمم" },
      { word_en: "Butcher", word_ar: "جزار", emoji: "🔪", difficulty: "easy", decoy_en: "Fishmonger", decoy_ar: "سماك" },
      { word_en: "Judge", word_ar: "قاضي", emoji: "👨‍⚖️", difficulty: "hard", decoy_en: "Lawyer", decoy_ar: "محامي" },
      { word_en: "Florist", word_ar: "بائع زهور", emoji: "💐", difficulty: "medium", decoy_en: "Gardener", decoy_ar: "بستاني" },
      { word_en: "Architect", word_ar: "معماري", emoji: "🏛️", difficulty: "hard", decoy_en: "Draftsman", decoy_ar: "رسام هندسي" },
      { word_en: "Flight Attendant", word_ar: "مضيفة طيران", emoji: "🛫", difficulty: "medium", decoy_en: "Guide", decoy_ar: "مرشد" },
      { word_en: "Electrician", word_ar: "كهربائي", emoji: "⚡", difficulty: "medium", decoy_en: "Linesman", decoy_ar: "فني خطوط" },
      { word_en: "Jeweler", word_ar: "جواهرجي", emoji: "💎", difficulty: "hard", decoy_en: "Goldsmith", decoy_ar: "صائغ" },
      { word_en: "Painter", word_ar: "دهان", emoji: "🖌️", difficulty: "easy", decoy_en: "Artist", decoy_ar: "فنان" },
      { word_en: "Coach", word_ar: "مدرب", emoji: "📣", difficulty: "easy", decoy_en: "Trainer", decoy_ar: "معد بدني" },
      { word_en: "Mailman", word_ar: "ساعي بريد", emoji: "📮", difficulty: "easy", decoy_en: "Courier", decoy_ar: "عامل توصيل" }
    ],
    technology: [
      { word_en: "Smartphone", word_ar: "هاتف ذكي", emoji: "📱", difficulty: "easy", decoy_en: "Tablet", decoy_ar: "تابلت" },
      { word_en: "Laptop", word_ar: "لابتوب", emoji: "💻", difficulty: "easy", decoy_en: "Desktop", decoy_ar: "كمبيوتر مكتب" },
      { word_en: "Robot", word_ar: "روبوت", emoji: "🤖", difficulty: "medium", decoy_en: "Android", decoy_ar: "أندرويد" },
      { word_en: "Internet", word_ar: "إنترنت", emoji: "🌐", difficulty: "easy", decoy_en: "Intranet", decoy_ar: "إنترانت" },
      { word_en: "Satellite", word_ar: "قمر صناعي", emoji: "🛰️", difficulty: "medium", decoy_en: "Telescope", decoy_ar: "تلسكوب" },
      { word_en: "Battery", word_ar: "بطارية", emoji: "🔋", difficulty: "easy", decoy_en: "Generator", decoy_ar: "مولد" },
      { word_en: "Microscope", word_ar: "مجهر", emoji: "🔬", difficulty: "medium", decoy_en: "Magnifying Glass", decoy_ar: "عدسة مكبرة" },
      { word_en: "Drone", word_ar: "درون", emoji: "🚁", difficulty: "medium", decoy_en: "Helicopter", decoy_ar: "هليكوبتر" },
      { word_en: "Bitcoin", word_ar: "بيتكوين", emoji: "₿", difficulty: "medium", decoy_en: "Gold", decoy_ar: "ذهب" },
      { word_en: "Cloud", word_ar: "سحابة", emoji: "☁️", difficulty: "medium", decoy_en: "Server", decoy_ar: "سيرفر" },
      { word_en: "Camera", word_ar: "كاميرا", emoji: "📷", difficulty: "easy", decoy_en: "Lens", decoy_ar: "عدسة" },
      { word_en: "Bluetooth", word_ar: "بلوتوث", emoji: "🦷", difficulty: "hard", decoy_en: "WiFi", decoy_ar: "واي فاي" },
      { word_en: "Keyboard", word_ar: "لوحة مفاتيح", emoji: "⌨️", difficulty: "easy", decoy_en: "Typewriter", decoy_ar: "آلة كاتبة" },
      { word_en: "VR Headset", word_ar: "نظارة واقع افتراضي", emoji: "🥽", difficulty: "medium", decoy_en: "Goggles", decoy_ar: "نظارات واقية" },
      { word_en: "Circuit", word_ar: "دائرة كهربائية", emoji: "🔌", difficulty: "hard", decoy_en: "Wire", decoy_ar: "سلك" },
      { word_en: "Laser", word_ar: "ليزر", emoji: "🔦", difficulty: "medium", decoy_en: "Flashlight", decoy_ar: "كشاف" },
      { word_en: "App", word_ar: "تطبيق", emoji: "📲", difficulty: "easy", decoy_en: "Website", decoy_ar: "موقع" },
      { word_en: "Password", word_ar: "كلمة مرور", emoji: "🔑", difficulty: "easy", decoy_en: "Username", decoy_ar: "اسم مستخدم" },
      { word_en: "Algorithm", word_ar: "خوارزمية", emoji: "🧮", difficulty: "hard", decoy_en: "Formula", decoy_ar: "معادلة" },
      { word_en: "Database", word_ar: "قاعدة بيانات", emoji: "🗄️", difficulty: "hard", decoy_en: "Spreadsheet", decoy_ar: "جدول بيانات" },
      { word_en: "Processor", word_ar: "معالج", emoji: "🧠", difficulty: "hard", decoy_en: "Engine", decoy_ar: "محرك" },
      { word_en: "Monitor", word_ar: "شاشة", emoji: "🖥️", difficulty: "easy", decoy_en: "TV", decoy_ar: "تلفزيون" },
      { word_en: "Mouse", word_ar: "ماوس", emoji: "🖱️", difficulty: "easy", decoy_en: "Trackpad", decoy_ar: "تراك باد" },
      { word_en: "Printer", word_ar: "طابعة", emoji: "🖨️", difficulty: "medium", decoy_en: "Scanner", decoy_ar: "سكانر" },
      { word_en: "Hard Drive", word_ar: "قرص صلب", emoji: "💾", difficulty: "medium", decoy_en: "Memory Card", decoy_ar: "كارت ميموري" },
      { word_en: "Router", word_ar: "راوتر", emoji: "📶", difficulty: "medium", decoy_en: "Modem", decoy_ar: "مودم" },
      { word_en: "Website", word_ar: "موقع إلكتروني", emoji: "💻", difficulty: "easy", decoy_en: "Blog", decoy_ar: "مدونة" },
      { word_en: "Software", word_ar: "برمجيات", emoji: "💿", difficulty: "medium", decoy_en: "Hardware", decoy_ar: "عتاد" },
      { word_en: "AI", word_ar: "ذكاء اصطناعي", emoji: "🤖", difficulty: "medium", decoy_en: "Machine", decoy_ar: "آلة" },
      { word_en: "USB", word_ar: "يو إس بي", emoji: "🔌", difficulty: "medium", decoy_en: "Cable", decoy_ar: "كابل" },
      { word_en: "Charger", word_ar: "شاحن", emoji: "🔌", difficulty: "easy", decoy_en: "Adapter", decoy_ar: "محول" },
      { word_en: "Server", word_ar: "خادم", emoji: "🏢", difficulty: "hard", decoy_en: "Data Center", decoy_ar: "مركز بيانات" },
      { word_en: "Pixel", word_ar: "بكسل", emoji: "🟦", difficulty: "hard", decoy_en: "Point", decoy_ar: "نقطة" },
      { word_en: "Coding", word_ar: "برمجة", emoji: "⌨️", difficulty: "medium", decoy_en: "Typing", decoy_ar: "كتابة" },
      { word_en: "Bug", word_ar: "خطأ برمجيا", emoji: "🪲", difficulty: "medium", decoy_en: "Virus", decoy_ar: "فيروس" },
      { word_en: "Encryption", word_ar: "تشفير", emoji: "🔐", difficulty: "hard", decoy_en: "Lock", decoy_ar: "قفل" },
      { word_en: "Fiber Optic", word_ar: "ألياف ضوئية", emoji: "➰", difficulty: "hard", decoy_en: "Copper Wire", decoy_ar: "سلك نحاسي" },
      { word_en: "Microchip", word_ar: "شريحة", emoji: "🔳", difficulty: "hard", decoy_en: "Transistor", decoy_ar: "ترانزستور" },
      { word_en: "Search Engine", word_ar: "محرك بحث", emoji: "🔍", difficulty: "medium", decoy_en: "Directory", decoy_ar: "دليل" },
      { word_en: "Social Media", word_ar: "تواصل اجتماعي", emoji: "📱", difficulty: "easy", decoy_en: "Messaging", decoy_ar: "مراسلة" }
    ],
    movies: [
      { word_en: "Avatar", word_ar: "أفاتار", emoji: "🟦", difficulty: "medium", decoy_en: "Pocahontas", decoy_ar: "بوكاهونتاس" },
      { word_en: "Titanic", word_ar: "تيتانيك", emoji: "🚢", difficulty: "easy", decoy_en: "Cruise", decoy_ar: "سفينة سياحية" },
      { word_en: "Batman", word_ar: "باتمان", emoji: "🦇", difficulty: "easy", decoy_en: "Dracula", decoy_ar: "دراكولا" },
      { word_en: "Star Wars", word_ar: "حرب النجوم", emoji: "⚔️", difficulty: "easy", decoy_en: "Star Trek", decoy_ar: "ستار تريك" },
      { word_en: "Harry Potter", word_ar: "هاري بوتر", emoji: "🪄", difficulty: "easy", decoy_en: "Lord of the Rings", decoy_ar: "سيد الخواتم" },
      { word_en: "The Lion King", word_ar: "الأسد الملك", emoji: "🦁", difficulty: "easy", decoy_en: "Tarzan", decoy_ar: "طارزان" },
      { word_en: "Joker", word_ar: "جوكر", emoji: "🤡", difficulty: "medium", decoy_en: "Clown", decoy_ar: "مهرج" },
      { word_en: "Inception", word_ar: "إنسبشن", emoji: "🌀", difficulty: "hard", decoy_en: "Interstellar", decoy_ar: "إنترستيلر" },
      { word_en: "Spider-Man", word_ar: "سبايدر مان", emoji: "🕷️", difficulty: "easy", decoy_en: "Venom", decoy_ar: "فينوم" },
      { word_en: "The Godfather", word_ar: "العراب", emoji: "🌹", difficulty: "hard", decoy_en: "Goodfellas", decoy_ar: "أصدقاء الطيبين" },
      { word_en: "Jurassic Park", word_ar: "حديقة الديناصورات", emoji: "🦖", difficulty: "medium", decoy_en: "Godzilla", decoy_ar: "غودزيلا" },
      { word_en: "Toy Story", word_ar: "حكاية لعبة", emoji: "🧸", difficulty: "easy", decoy_en: "Small Soldiers", decoy_ar: "جنود صغار" },
      { word_en: "The Matrix", word_ar: "الماتريكس", emoji: "🕶️", difficulty: "hard", decoy_en: "Blade Runner", decoy_ar: "بليد رانر" },
      { word_en: "Frozen", word_ar: "فروزن", emoji: "❄️", difficulty: "easy", decoy_en: "Tangled", decoy_ar: "تانجلد" },
      { word_en: "Home Alone", word_ar: "وحدي في المنزل", emoji: "🏠", difficulty: "easy", decoy_en: "The Grinch", decoy_ar: "الغرينش" },
      { word_en: "Gladiator", word_ar: "غلادياتور", emoji: "⚔️", difficulty: "hard", decoy_en: "Spartacus", decoy_ar: "سبارتاكوس" },
      { word_en: "Fast & Furious", word_ar: "فاست آند فيوريوس", emoji: "🏎️", difficulty: "easy", decoy_en: "Need for Speed", decoy_ar: "نيد فور سبيد" },
      { word_en: "Iron Man", word_ar: "آيرون مان", emoji: "🦾", difficulty: "medium", decoy_en: "RoboCop", decoy_ar: "روبوكوب" },
      { word_en: "Shrek", word_ar: "شريك", emoji: "🧅", difficulty: "easy", decoy_en: "Hulk", decoy_ar: "هولك" },
      { word_en: "Minions", word_ar: "مينيونز", emoji: "🍌", difficulty: "easy", decoy_en: "The Smurfs", decoy_ar: "السنافر" },
      { word_en: "Pirates of the Caribbean", word_ar: "قراصنة الكاريبي", emoji: "🏴‍☠️", difficulty: "medium", decoy_en: "Peter Pan", decoy_ar: "بيتر بان" },
      { word_en: "The Avengers", word_ar: "أفنجرز", emoji: "🅰️", difficulty: "medium", decoy_en: "Justice League", decoy_ar: "جاستس ليج" },
      { word_en: "Ice Age", word_ar: "عصر الجليد", emoji: "🌰", difficulty: "easy", decoy_en: "Madagascar", decoy_ar: "مدغشقر" },
      { word_en: "Sherlock Holmes", word_ar: "شيرلوك هولمز", emoji: "🔍", difficulty: "hard", decoy_en: "Hercule Poirot", decoy_ar: "هيركيول بوارو" },
      { word_en: "The Terminator", word_ar: "ترمينتور", emoji: "🤖", difficulty: "hard", decoy_en: "I, Robot", decoy_ar: "أنا روبوت" },
      { word_en: "Kung Fu Panda", word_ar: "كونغ فو باندا", emoji: "🐼", difficulty: "easy", decoy_en: "Mulan", decoy_ar: "مولان" },
      { word_en: "Finding Nemo", word_ar: "البحث عن نيمو", emoji: "🐠", difficulty: "easy", decoy_en: "Shark Tale", decoy_ar: "إشاعة القرش" },
      { word_en: "Superman", word_ar: "سوبرمان", emoji: "🦸", difficulty: "easy", decoy_en: "Hancock", decoy_ar: "هانكوك" },
      { word_en: "Transformers", word_ar: "ترانسفورمرز", emoji: "🚛", difficulty: "medium", decoy_en: "Gundam", decoy_ar: "غاندام" },
      { word_en: "Moana", word_ar: "موانا", emoji: "🐚", difficulty: "medium", decoy_en: "Lilo & Stitch", decoy_ar: "ليلو وستيتش" },
      { word_en: "Zootopia", word_ar: "زوتوبيا", emoji: "🦊", difficulty: "medium", decoy_en: "Sing", decoy_ar: "سينغ" },
      { word_en: "Ratatouille", word_ar: "راتاتوي", emoji: "🐀", difficulty: "medium", decoy_en: "Stuart Little", decoy_ar: "ستيوارت ليتل" },
      { word_en: "Up", word_ar: "فوق", emoji: "🎈", difficulty: "medium", decoy_en: "Despicable Me", decoy_ar: "أنا الحقير" },
      { word_en: "The Mask", word_ar: "القناع", emoji: "👺", difficulty: "medium", decoy_en: "Beetlejuice", decoy_ar: "بيتلجوس" },
      { word_en: "Aladdin", word_ar: "علاء الدين", emoji: "🧞", difficulty: "easy", decoy_en: "Sinbad", decoy_ar: "سندباد" },
      { word_en: "Coco", word_ar: "كوكو", emoji: "🎸", difficulty: "hard", decoy_en: "The Book of Life", decoy_ar: "كتاب الحياة" },
      { word_en: "Cars", word_ar: "سيارات", emoji: "⚡", difficulty: "easy", decoy_en: "Planes", decoy_ar: "طائرات" },
      { word_en: "Deadpool", word_ar: "ديدبول", emoji: "⚔️", difficulty: "hard", decoy_en: "Wolverine", decoy_ar: "ولفرين" },
      { word_en: "John Wick", word_ar: "جون ويك", emoji: "🐶", difficulty: "hard", decoy_en: "The Equalizer", decoy_ar: "المعادل" },
      { word_en: "Jumanji", word_ar: "جومانجي", emoji: "🎲", difficulty: "medium", decoy_en: "Zathura", decoy_ar: "زاثورا" }
    ],
    music: [
      { word_en: "Guitar", word_ar: "جيتار", emoji: "🎸", difficulty: "easy", decoy_en: "Bass", decoy_ar: "باس" },
      { word_en: "Piano", word_ar: "بيانو", emoji: "🎹", difficulty: "easy", decoy_en: "Organ", decoy_ar: "أورج" },
      { word_en: "Drums", word_ar: "طبول", emoji: "🥁", difficulty: "easy", decoy_en: "Percussion", decoy_ar: "إيقاع" },
      { word_en: "Violin", word_ar: "كمان", emoji: "🎻", difficulty: "medium", decoy_en: "Cello", decoy_ar: "تشيلو" },
      { word_en: "Microphone", word_ar: "ميكروفون", emoji: "🎤", difficulty: "easy", decoy_en: "Speaker", decoy_ar: "سماعة" },
      { word_en: "Saxophone", word_ar: "ساكسفون", emoji: "🎷", difficulty: "medium", decoy_en: "Trumpet", decoy_ar: "ترومبيت" },
      { word_en: "DJ", word_ar: "دي جي", emoji: "🎧", difficulty: "easy", decoy_en: "Producer", decoy_ar: "منتج" },
      { word_en: "Orchestra", word_ar: "أوركسترا", emoji: "🎼", difficulty: "medium", decoy_en: "Band", decoy_ar: "فرقة" },
      { word_en: "Opera", word_ar: "أوبرا", emoji: "🎭", difficulty: "hard", decoy_en: "Ballet", decoy_ar: "باليه" },
      { word_en: "Hip Hop", word_ar: "هيب هوب", emoji: "👟", difficulty: "medium", decoy_en: "Rap", decoy_ar: "راب" },
      { word_en: "Jazz", word_ar: "جاز", emoji: "🎷", difficulty: "hard", decoy_en: "Blues", decoy_ar: "بلوز" },
      { word_en: "Rock", word_ar: "روك", emoji: "🤘", difficulty: "easy", decoy_en: "Metal", decoy_ar: "ميتال" },
      { word_en: "Pop", word_ar: "بوب", emoji: "🍭", difficulty: "easy", decoy_en: "Country", decoy_ar: "كانتري" },
      { word_en: "Flute", word_ar: "ناي", emoji: "🎶", difficulty: "medium", decoy_en: "Clarinet", decoy_ar: "كلارينيت" },
      { word_en: "Trumpet", word_ar: "بوق", emoji: "🎺", difficulty: "medium", decoy_en: "Trombone", decoy_ar: "ترومبون" },
      { word_en: "Accordion", word_ar: "أكورديون", emoji: "🪗", difficulty: "hard", decoy_en: "Harmonica", decoy_ar: "هارمونيكا" },
      { word_en: "Concert", word_ar: "حفل موسيقي", emoji: "🏟️", difficulty: "easy", decoy_en: "Festival", decoy_ar: "مهرجان" },
      { word_en: "Album", word_ar: "ألبوم", emoji: "💿", difficulty: "easy", decoy_en: "Playlist", decoy_ar: "قائمة تشغيل" },
      { word_en: "Lyrics", word_ar: "كلمات الأغاني", emoji: "📝", difficulty: "medium", decoy_en: "Poetry", decoy_ar: "شعر" },
      { word_en: "Chorus", word_ar: "كورس", emoji: "🎤", difficulty: "hard", decoy_en: "Verse", decoy_ar: "مقطع شعري" },
      { word_en: "Radio", word_ar: "راديو", emoji: "📻", difficulty: "easy", decoy_en: "Podcast", decoy_ar: "بودكاست" },
      { word_en: "Headphones", word_ar: "سماعات الرأس", emoji: "🎧", difficulty: "easy", decoy_en: "Earbuds", decoy_ar: "سماعات أذن" },
      { word_en: "Volume", word_ar: "مستوى الصوت", emoji: "🔊", difficulty: "easy", decoy_en: "Bass", decoy_ar: "باس" },
      { word_en: "Rhythm", word_ar: "إيقاع", emoji: "🥁", difficulty: "hard", decoy_en: "Tempo", decoy_ar: "سرعة الإيقاع" },
      { word_en: "Recording", word_ar: "تسجيل", emoji: "⏺️", difficulty: "medium", decoy_en: "Broadcast", decoy_ar: "بث" },
      { word_en: "Harp", word_ar: "قيثارة", emoji: "🪕", difficulty: "hard", decoy_en: "Lyre", decoy_ar: "ليرة" },
      { word_en: "Bagpipes", word_ar: "مزمار القربة", emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", difficulty: "hard", decoy_en: "Harmonica", decoy_ar: "هارمونيكا" },
      { word_en: "Tambourine", word_ar: "رق", emoji: "🪘", difficulty: "hard", decoy_en: "Triangle", decoy_ar: "مثلث" },
      { word_en: "Synthesizer", word_ar: "سنثسيزر", emoji: "🎹", difficulty: "hard", decoy_en: "Keyboard", decoy_ar: "لوحة مفاتيح" },
      { word_en: "Composer", word_ar: "ملحن", emoji: "🖋️", difficulty: "hard", decoy_en: "Conductor", decoy_ar: "مايسترو" },
      { word_en: "Karaoke", word_ar: "كاريوكي", emoji: "🎤", difficulty: "easy", decoy_en: "Open Mic", decoy_ar: "ميكروفون مفتوح" },
      { word_en: "MP3 Player", word_ar: "مشغل موسيقى", emoji: "📟", difficulty: "medium", decoy_en: "CD Player", decoy_ar: "مشغل أقراص" },
      { word_en: "Disco", word_ar: "ديسكو", emoji: "🪩", difficulty: "medium", decoy_en: "Nightclub", decoy_ar: "ملهى ليلي" },
      { word_en: "Classical", word_ar: "كلاسيكي", emoji: "🎻", difficulty: "medium", decoy_en: "Baroque", decoy_ar: "باروك" },
      { word_en: "Lullaby", word_ar: "تهويدة", emoji: "🌙", difficulty: "hard", decoy_en: "Hymn", decoy_ar: "ترنيمة" },
      { word_en: "Playlist", word_ar: "قائمة تشغيل", emoji: "📜", difficulty: "easy", decoy_en: "Library", decoy_ar: "مكتبة" },
      { word_en: "Gramophone", word_ar: "جراموفون", emoji: "🎺", difficulty: "hard", decoy_en: "Turntable", decoy_ar: "مشغل أسطوانات" },
      { word_en: "Melody", word_ar: "لحن", emoji: "🎵", difficulty: "hard", decoy_en: "Harmony", decoy_ar: "تناغم" },
      { word_en: "Beat", word_ar: "نبض", emoji: "💓", difficulty: "medium", decoy_en: "Pulse", decoy_ar: "نبض" },
      { word_en: "Solo", word_ar: "منفرد", emoji: "👤", difficulty: "medium", decoy_en: "Duet", decoy_ar: "ثنائي" }
    ],
    body_parts: [
      { word_en: "Brain", word_ar: "دماغ", emoji: "🧠", difficulty: "easy", decoy_en: "Skull", decoy_ar: "جمجمة" },
      { word_en: "Heart", word_ar: "قلب", emoji: "❤️", difficulty: "easy", decoy_en: "Lung", decoy_ar: "رئة" },
      { word_en: "Eyes", word_ar: "عيون", emoji: "👀", difficulty: "easy", decoy_en: "Glasses", decoy_ar: "نظارات" },
      { word_en: "Hands", word_ar: "يدين", emoji: "🙌", difficulty: "easy", decoy_en: "Gloves", decoy_ar: "قفازات" },
      { word_en: "Skeleton", word_ar: "هيكل عظمي", emoji: "💀", difficulty: "medium", decoy_en: "Muscle", decoy_ar: "عضلة" },
      { word_en: "Fingerprint", word_ar: "بصمة", emoji: "🖐️", difficulty: "medium", decoy_en: "Handprint", decoy_ar: "بصمة يد" },
      { word_en: "Teeth", word_ar: "أسنان", emoji: "🦷", difficulty: "easy", decoy_en: "Gums", decoy_ar: "لثة" },
      { word_en: "Lungs", word_ar: "رئتين", emoji: "🫁", difficulty: "medium", decoy_en: "Bronchi", decoy_ar: "شعب هوائية" },
      { word_en: "Ear", word_ar: "أذن", emoji: "👂", difficulty: "easy", decoy_en: "Earring", decoy_ar: "قرط" },
      { word_en: "Nose", word_ar: "أنف", emoji: "👃", difficulty: "easy", decoy_en: "Nostril", decoy_ar: "منخر" },
      { word_en: "Leg", word_ar: "ساق", emoji: "🦵", difficulty: "easy", decoy_en: "Foot", decoy_ar: "قدم" },
      { word_en: "Stomach", word_ar: "معدة", emoji: "🤰", difficulty: "easy", decoy_en: "Belly", decoy_ar: "بطن" },
      { word_en: "Muscle", word_ar: "عضلة", emoji: "💪", difficulty: "medium", decoy_en: "Tendon", decoy_ar: "وتر" },
      { word_en: "Blood", word_ar: "دم", emoji: "🩸", difficulty: "medium", decoy_en: "Plasma", decoy_ar: "بلازما" },
      { word_en: "Spine", word_ar: "عمود فقري", emoji: "🦴", difficulty: "hard", decoy_en: "Backbone", decoy_ar: "عظمة الظهر" },
      { word_en: "Liver", word_ar: "كبد", emoji: "🥩", difficulty: "hard", decoy_en: "Kidney", decoy_ar: "كلية" },
      { word_en: "Shoulder", word_ar: "كتف", emoji: "🤷", difficulty: "easy", decoy_en: "Collarbone", decoy_ar: "عظم الترقوة" },
      { word_en: "Wrist", word_ar: "معصم", emoji: "⌚", difficulty: "medium", decoy_en: "Ankle", decoy_ar: "كاحل" },
      { word_en: "Tongue", word_ar: "لسان", emoji: "👅", difficulty: "easy", decoy_en: "Uvula", decoy_ar: "لهاة" },
      { word_en: "Hair", word_ar: "شعر", emoji: "💇", difficulty: "easy", decoy_en: "Fur", decoy_ar: "فراء" },
      { word_en: "Thumb", word_ar: "إبهام", emoji: "👍", difficulty: "easy", decoy_en: "Index Finger", decoy_ar: "سبابة" },
      { word_en: "Knee", word_ar: "ركبة", emoji: "🦵", difficulty: "easy", decoy_en: "Elbow", decoy_ar: "كوع" },
      { word_en: "Ribs", word_ar: "أضلاع", emoji: "🩻", difficulty: "hard", decoy_en: "Cage", decoy_ar: "قفص" },
      { word_en: "Skull", word_ar: "جمجمة", emoji: "💀", difficulty: "medium", decoy_en: "Head", decoy_ar: "رأس" },
      { word_en: "Neck", word_ar: "رقبة", emoji: "🦒", difficulty: "easy", decoy_en: "Throat", decoy_ar: "حلق" },
      { word_en: "Back", word_ar: "ظهر", emoji: "🕴️", difficulty: "easy", decoy_en: "Spine", decoy_ar: "عمود فقري" },
      { word_en: "Bone", word_ar: "عظم", emoji: "🦴", difficulty: "easy", decoy_en: "Cartilage", decoy_ar: "غضروف" },
      { word_en: "Nail", word_ar: "ظفر", emoji: "💅", difficulty: "easy", decoy_en: "Claw", decoy_ar: "مخلب" },
      { word_en: "Skin", word_ar: "جلد", emoji: "🧴", difficulty: "medium", decoy_en: "Pore", decoy_ar: "مسام" },
      { word_en: "Foot", word_ar: "قدم", emoji: "🦶", difficulty: "easy", decoy_en: "Toe", decoy_ar: "إصبع قدم" },
      { word_en: "Elbow", word_ar: "كوع", emoji: "💪", difficulty: "medium", decoy_en: "Knee", decoy_ar: "ركبة" },
      { word_en: "Cheek", word_ar: "خد", emoji: "😊", difficulty: "medium", decoy_en: "Jaw", decoy_ar: "فك" },
      { word_en: "Eyelash", word_ar: "رمش", emoji: "👁️", difficulty: "hard", decoy_en: "Eyebrow", decoy_ar: "حاجب" },
      { word_en: "Chin", word_ar: "ذقن", emoji: "🧔", difficulty: "medium", decoy_en: "Beard", decoy_ar: "لحيّة" },
      { word_en: "Kidney", word_ar: "كلية", emoji: "🥣", difficulty: "hard", decoy_en: "Bladder", decoy_ar: "مثانة" },
      { word_en: "Ankle", word_ar: "كاحل", emoji: "👟", difficulty: "medium", decoy_en: "Heel", decoy_ar: "كعب" },
      { word_en: "Palm", word_ar: "كف", emoji: "✋", difficulty: "medium", decoy_en: "Sole", decoy_ar: "باطن القدم" },
      { word_en: "Hip", word_ar: "ورك", emoji: "👖", difficulty: "hard", decoy_en: "Waist", decoy_ar: "خصر" },
      { word_en: "Diaphragm", word_ar: "حجاب حاجز", emoji: "🌬️", difficulty: "hard", decoy_en: "Abs", decoy_ar: "عضلات بطن" },
      { word_en: "Pancreas", word_ar: "بنكرياس", emoji: "🧬", difficulty: "hard", decoy_en: "Spleen", decoy_ar: "طحال" }
    ],
    vehicles: [
      { word_en: "Airplane", word_ar: "طائرة", emoji: "✈️", difficulty: "easy", decoy_en: "Helicopter", decoy_ar: "هليكوبتر" },
      { word_en: "Ship", word_ar: "سفينة", emoji: "🚢", difficulty: "easy", decoy_en: "Boat", decoy_ar: "قارب" },
      { word_en: "Bicycle", word_ar: "دراجة", emoji: "🚲", difficulty: "easy", decoy_en: "Scooter", decoy_ar: "سكوتر" },
      { word_en: "Submarine", word_ar: "غواصة", emoji: "⚓", difficulty: "medium", decoy_en: "U-Boat", decoy_ar: "يو-بوت" },
      { word_en: "Rocket", word_ar: "صاروخ", emoji: "🚀", difficulty: "medium", decoy_en: "Spaceship", decoy_ar: "سفينة فضاء" },
      { word_en: "Truck", word_ar: "شاحنة", emoji: "🚚", difficulty: "easy", decoy_en: "Van", decoy_ar: "فان" },
      { word_en: "Train", word_ar: "قطار", emoji: "🚂", difficulty: "easy", decoy_en: "Tram", decoy_ar: "ترام" },
      { word_en: "Bus", word_ar: "حافلة", emoji: "🚌", difficulty: "easy", decoy_en: "Minibus", decoy_ar: "ميكروباص" },
      { word_en: "Ambulance", word_ar: "إسعاف", emoji: "🚑", difficulty: "easy", decoy_en: "Fire Truck", decoy_ar: "عربة إطفاء" },
      { word_en: "Tank", word_ar: "دبابة", emoji: "💣", difficulty: "medium", decoy_en: "Armored Car", decoy_ar: "مدرعة" },
      { word_en: "Helicopter", word_ar: "هليكوبتر", emoji: "🚁", difficulty: "medium", decoy_en: "Jet", decoy_ar: "طائرة نفاثة" },
      { word_en: "Taxi", word_ar: "تاكسي", emoji: "🚕", difficulty: "easy", decoy_en: "Uber", decoy_ar: "أوبر" },
      { word_en: "Motorcycle", word_ar: "دراجة نارية", emoji: "🏍️", difficulty: "easy", decoy_en: "Quad Bike", decoy_ar: "بيتش باجي" },
      { word_en: "Hot Air Balloon", word_ar: "منطاد", emoji: "🎈", difficulty: "hard", decoy_en: "Blimp", decoy_ar: "منطاد هواء" },
      { word_en: "Tractor", word_ar: "جرار", emoji: "🚜", difficulty: "medium", decoy_en: "Bulldozer", decoy_ar: "بلدوزر" },
      { word_en: "Canoe", word_ar: "كانو", emoji: "🚣", difficulty: "hard", decoy_en: "Kayak", decoy_ar: "كاياك" },
      { word_en: "Skateboard", word_ar: "سكيت بورد", emoji: "🛹", difficulty: "easy", decoy_en: "Roller Skates", decoy_ar: "باتيناج" },
      { word_en: "Cruise Ship", word_ar: "سفينة سياحية", emoji: "🛳️", difficulty: "medium", decoy_en: "Yacht", decoy_ar: "يخت" },
      { word_en: "Crane", word_ar: "ونش", emoji: "🏗️", difficulty: "medium", decoy_en: "Excavator", decoy_ar: "حفار" },
      { word_en: "Scooter", word_ar: "سكوتر", emoji: "🛴", difficulty: "easy", decoy_en: "Moped", decoy_ar: "موبيد" },
      { word_en: "Go-kart", word_ar: "جو كارت", emoji: "🏎️", difficulty: "hard", decoy_en: "F1 Car", decoy_ar: "سيارة فورميلا 1" },
      { word_en: "Caravan", word_ar: "كارفان", emoji: "🚐", difficulty: "medium", decoy_en: "Trailer", decoy_ar: "مقطورة" },
      { word_en: "Gondola", word_ar: "جندول", emoji: "🛶", difficulty: "hard", decoy_en: "Ferry", decoy_ar: "معدية" },
      { word_en: "Jet Ski", word_ar: "جت سكي", emoji: "🌊", difficulty: "medium", decoy_en: "Speedboat", decoy_ar: "لانش" },
      { word_en: "Rickshaw", word_ar: "توك توك", emoji: "🛺", difficulty: "medium", decoy_en: "Tricycle", decoy_ar: "دراجة ثلاثية" },
      { word_en: "Unicycle", word_ar: "دراجة أحادية", emoji: "🎡", difficulty: "hard", decoy_en: "Bicycle", decoy_ar: "دراجة" },
      { word_en: "Forklift", word_ar: "رافعة شوكية", emoji: "📦", difficulty: "hard", decoy_en: "Pallet Jack", decoy_ar: "جاك" },
      { word_en: "Concrete Mixer", word_ar: "خلاطة خرسانة", emoji: "🏗️", difficulty: "hard", decoy_en: "Dump Truck", decoy_ar: "قلاب" },
      { word_en: "Snowmobile", word_ar: "عربة ثلج", emoji: "❄️", difficulty: "medium", decoy_en: "Sled", decoy_ar: "زلاجة" },
      { word_en: "Car", word_ar: "سيارة", emoji: "🚗", difficulty: "easy", decoy_en: "SUV", decoy_ar: "سيارة دفع رباعي" },
      { word_en: "Van", word_ar: "فان", emoji: "🚐", difficulty: "easy", decoy_en: "Minivan", decoy_ar: "ميني فان" },
      { word_en: "Hoverboard", word_ar: "هوفربورد", emoji: "🛹", difficulty: "medium", decoy_en: "Segway", decoy_ar: "سيجواي" },
      { word_en: "Steam Train", word_ar: "قطار بخاري", emoji: "🚂", difficulty: "hard", decoy_en: "Metro", decoy_ar: "مترو" },
      { word_en: "Golf Cart", word_ar: "عربة جولف", emoji: "⛳", difficulty: "medium", decoy_en: "Buggy", decoy_ar: "باجي" },
      { word_en: "Zeppelin", word_ar: "منطاد زيبلين", emoji: "🏢", difficulty: "hard", decoy_en: "Balloon", decoy_ar: "بالون" },
      { word_en: "Tow Truck", word_ar: "ونش إنقاذ", emoji: "🪝", difficulty: "medium", decoy_en: "Wrecker", decoy_ar: "ريكشر" },
      { word_en: "Cargo Plane", word_ar: "طائرة شحن", emoji: "📦", difficulty: "medium", decoy_en: "Military Jet", decoy_ar: "طائرة عسكرية" },
      { word_en: "Police Car", word_ar: "سيارة شرطة", emoji: "🚓", difficulty: "easy", decoy_en: "Patrol Car", decoy_ar: "سيارة دورية" },
      { word_en: "Fire Engine", word_ar: "عربة مطافئ", emoji: "🚒", difficulty: "easy", decoy_en: "Ladder Truck", decoy_ar: "شاحنة سلم" },
      { word_en: "Segway", word_ar: "سيجواي", emoji: "🛴", difficulty: "hard", decoy_en: "Unicycle", decoy_ar: "أحادية" }
    ],
    nature: [
      { word_en: "Volcano", word_ar: "بركان", emoji: "🌋", difficulty: "medium", decoy_en: "Mountain", decoy_ar: "جبل" },
      { word_en: "Waterfall", word_ar: "شلال", emoji: "🌊", difficulty: "easy", decoy_en: "River", decoy_ar: "نهر" },
      { word_en: "Desert", word_ar: "صحراء", emoji: "🏜️", difficulty: "easy", decoy_en: "Dune", decoy_ar: "كثبان" },
      { word_en: "Forest", word_ar: "غابة", emoji: "🌲", difficulty: "easy", decoy_en: "Jungle", decoy_ar: "غابة استوائية" },
      { word_en: "Cactus", word_ar: "صبار", emoji: "🌵", difficulty: "easy", decoy_en: "Aloe", decoy_ar: "ألوفيرا" },
      { word_en: "Mushroom", word_ar: "فطر", emoji: "🍄", difficulty: "easy", decoy_en: "Toadstool", decoy_ar: "فطر سام" },
      { word_en: "Tornado", word_ar: "إعصار", emoji: "🌪️", difficulty: "medium", decoy_en: "Hurricane", decoy_ar: "إعصار استوائي" },
      { word_en: "Earthquake", word_ar: "زلزال", emoji: "🫨", difficulty: "medium", decoy_en: "Tremor", decoy_ar: "هزة" },
      { word_en: "Rainbow", word_ar: "قوس قزح", emoji: "🌈", difficulty: "easy", decoy_en: "Prism", decoy_ar: "منشور" },
      { word_en: "Glacier", word_ar: "نهر جليدي", emoji: "🧊", difficulty: "hard", decoy_en: "Iceberg", decoy_ar: "جبل جليدي" },
      { word_en: "Island", word_ar: "جزيرة", emoji: "🏝️", difficulty: "easy", decoy_en: "Peninsula", decoy_ar: "شبه جزيرة" },
      { word_en: "Cave", word_ar: "كهف", emoji: "🕳️", difficulty: "medium", decoy_en: "Tunnel", decoy_ar: "نفق" },
      { word_en: "Ocean", word_ar: "محيط", emoji: "🌊", difficulty: "easy", decoy_en: "Sea", decoy_ar: "بحر" },
      { word_en: "Butterfly", word_ar: "فراشة", emoji: "🦋", difficulty: "easy", decoy_en: "Moth", decoy_ar: "عثة" },
      { word_en: "Honeycomb", word_ar: "خلية نحل", emoji: "⬢", difficulty: "hard", decoy_en: "Wasp Nest", decoy_ar: "عش دبابير" },
      { word_en: "Bamboo", word_ar: "خيزران", emoji: "🎋", difficulty: "medium", decoy_en: "Sugar Cane", decoy_ar: "قصب سكر" },
      { word_en: "Lightning", word_ar: "برق", emoji: "⚡", difficulty: "easy", decoy_en: "Thunder", decoy_ar: "رعد" },
      { word_en: "Autumn", word_ar: "الخريف", emoji: "🍂", difficulty: "medium", decoy_en: "Spring", decoy_ar: "الربيع" },
      { word_en: "Snowflake", word_ar: "ندفة ثلج", emoji: "❄️", difficulty: "easy", decoy_en: "Hail", decoy_ar: "برد" },
      { word_en: "Sunflower", word_ar: "دوار الشمس", emoji: "🌻", difficulty: "easy", decoy_en: "Daisy", decoy_ar: "أقحوان" },
      { word_en: "Beach", word_ar: "شاطئ", emoji: "🏖️", difficulty: "easy", decoy_en: "Shore", decoy_ar: "ساحل" },
      { word_en: "Coral Reef", word_ar: "شعب مرجانية", emoji: "🪸", difficulty: "medium", decoy_en: "Seaweed", decoy_ar: "طحالب" },
      { word_en: "Pine Cone", word_ar: "كوز صنوبر", emoji: "🌲", difficulty: "hard", decoy_en: "Acorn", decoy_ar: "بندق" },
      { word_en: "Fog", word_ar: "ضباب", emoji: "🌫️", difficulty: "medium", decoy_en: "Mist", decoy_ar: "رذاذ" },
      { word_en: "Diamond", word_ar: "ألماس", emoji: "💎", difficulty: "easy", decoy_en: "Coal", decoy_ar: "فحم" },
      { word_en: "Gold", word_ar: "ذهب", emoji: "💰", difficulty: "easy", decoy_en: "Copper", decoy_ar: "نحاس" },
      { word_en: "Volcanic Ash", word_ar: "رماد بركاني", emoji: "💨", difficulty: "hard", decoy_en: "Smoke", decoy_ar: "دخان" },
      { word_en: "Tide", word_ar: "مد وجزر", emoji: "🌊", difficulty: "hard", decoy_en: "Wave", decoy_ar: "موجة" },
      { word_en: "Eclipse", word_ar: "كسوف", emoji: "🌑", difficulty: "hard", decoy_en: "New Moon", decoy_ar: "قمر جديد" },
      { word_en: "Meteor", word_ar: "شهاب", emoji: "🌠", difficulty: "medium", decoy_en: "Comet", decoy_ar: "مذنب" },
      { word_en: "River", word_ar: "نهر", emoji: "🛶", difficulty: "easy", decoy_en: "Stream", decoy_ar: "جدول" },
      { word_en: "Oasis", word_ar: "واحة", emoji: "🌴", difficulty: "medium", decoy_en: "Spring", decoy_ar: "ينبوع" },
      { word_en: "Crater", word_ar: "فوهة", emoji: "🕳️", difficulty: "hard", decoy_en: "Pit", decoy_ar: "حفرة" },
      { word_en: "Valley", word_ar: "وادي", emoji: "🏞️", difficulty: "medium", decoy_en: "Canyon", decoy_ar: "أخدود" },
      { word_en: "Summit", word_ar: "قمة", emoji: "🧗", difficulty: "hard", decoy_en: "Peak", decoy_ar: "ذروة" },
      { word_en: "Vineyard", word_ar: "كرم عنب", emoji: "🍇", difficulty: "medium", decoy_en: "Orchard", decoy_ar: "بستان" },
      { word_en: "Savanna", word_ar: "سافانا", emoji: "🦁", difficulty: "hard", decoy_en: "Steppe", decoy_ar: "سهب" },
      { word_en: "Tundra", word_ar: "تندرا", emoji: "🧊", difficulty: "hard", decoy_en: "Permafrost", decoy_ar: "تربة صقيعية" },
      { word_en: "Fern", word_ar: "سرخس", emoji: "🌿", difficulty: "hard", decoy_en: "Moss", decoy_ar: "طحلب" },
      { word_en: "Lagoon", word_ar: "بحيرة ضحلة", emoji: "🏝️", difficulty: "hard", decoy_en: "Bay", decoy_ar: "خليج" }
    ],
    fashion: [
      { word_en: "Sunglasses", word_ar: "نظارات شمسية", emoji: "🕶️", difficulty: "easy", decoy_en: "Goggles", decoy_ar: "نظارات واقية" },
      { word_en: "T-Shirt", word_ar: "تي شيرت", emoji: "👕", difficulty: "easy", decoy_en: "Shirt", decoy_ar: "قميص" },
      { word_en: "Jeans", word_ar: "جينز", emoji: "👖", difficulty: "easy", decoy_en: "Trousers", decoy_ar: "بنطلون" },
      { word_en: "Dress", word_ar: "فستان", emoji: "👗", difficulty: "easy", decoy_en: "Skirt", decoy_ar: "تنورة" },
      { word_en: "High Heels", word_ar: "حذاء كعب عالٍ", emoji: "👠", difficulty: "easy", decoy_en: "Stilettos", decoy_ar: "خنجر" },
      { word_en: "Sneakers", word_ar: "حذاء رياضي", emoji: "👟", difficulty: "easy", decoy_en: "Running Shoes", decoy_ar: "حذاء جري" },
      { word_en: "Watch", word_ar: "ساعة يد", emoji: "⌚", difficulty: "easy", decoy_en: "Clock", decoy_ar: "ساعة حائط" },
      { word_en: "Backpack", word_ar: "حقيبة ظهر", emoji: "🎒", difficulty: "easy", decoy_en: "Handbag", decoy_ar: "حقيبة يد" },
      { word_en: "Suit", word_ar: "بدلة", emoji: "🤵", difficulty: "easy", decoy_en: "Tuxedo", decoy_ar: "توكسيدو" },
      { word_en: "Scarf", word_ar: "وشاح", emoji: "🧣", difficulty: "easy", decoy_en: "Shawl", decoy_ar: "شال" },
      { word_en: "Gloves", word_ar: "قفازات", emoji: "🧤", difficulty: "easy", decoy_en: "Mittens", decoy_ar: "قفازات صوف" },
      { word_en: "Hat", word_ar: "قبعة", emoji: "🎩", difficulty: "easy", decoy_en: "Cap", decoy_ar: "كاب" },
      { word_en: "Jewelry", word_ar: "مجوهرات", emoji: "💎", difficulty: "medium", decoy_en: "Trinkets", decoy_ar: "حلي" },
      { word_en: "Ring", word_ar: "خاتم", emoji: "💍", difficulty: "easy", decoy_en: "Band", decoy_ar: "دبلة" },
      { word_en: "Necklace", word_ar: "قلادة", emoji: "📿", difficulty: "easy", decoy_en: "Choker", decoy_ar: "شوكر" },
      { word_en: "Perfume", word_ar: "عطر", emoji: "🧴", difficulty: "easy", decoy_en: "Cologne", decoy_ar: "كولونيا" },
      { word_en: "Make-up", word_ar: "مكياج", emoji: "💄", difficulty: "medium", decoy_en: "Cosmetics", decoy_ar: "مستحضرات تجميل" },
      { word_en: "Umbrella", word_ar: "مظلة", emoji: "☂️", difficulty: "easy", decoy_en: "Parasol", decoy_ar: "شمسية" },
      { word_en: "Belt", word_ar: "حزام", emoji: "👔", difficulty: "easy", decoy_en: "Strap", decoy_ar: "سير" },
      { word_en: "Tie", word_ar: "ربطة عنق", emoji: "👔", difficulty: "easy", decoy_en: "Bowtie", decoy_ar: "فيونكة" },
      { word_en: "Lipstick", word_ar: "أحمر شفاه", emoji: "💄", difficulty: "easy", decoy_en: "Lip Balm", decoy_ar: "مرطب شفاه" },
      { word_en: "Wallet", word_ar: "محفظة", emoji: "👛", difficulty: "easy", decoy_en: "Purse", decoy_ar: "جزدان" },
      { word_en: "Raincoat", word_ar: "معطف مطر", emoji: "🧥", difficulty: "medium", decoy_en: "Trench Coat", decoy_ar: "ترنش كوت" },
      { word_en: "Pajamas", word_ar: "بيجاما", emoji: "🛌", difficulty: "easy", decoy_en: "Nightgown", decoy_ar: "قميص نوم" },
      { word_en: "Wallet", word_ar: "محفظة", emoji: "💼", difficulty: "easy", decoy_en: "Money Clip", decoy_ar: "مشبك نقود" },
      { word_en: "Socks", word_ar: "جوارب", emoji: "🧦", difficulty: "easy", decoy_en: "Stockings", decoy_ar: "شرابات" },
      { word_en: "Boots", word_ar: "أحذية طويلة", emoji: "🥾", difficulty: "easy", decoy_en: "Galoshes", decoy_ar: "كالوش" },
      { word_en: "Bikini", word_ar: "بيكيني", emoji: "👙", difficulty: "medium", decoy_en: "Swimsuit", decoy_ar: "ملابس سباحة" },
      { word_en: "Sandals", word_ar: "صنادل", emoji: "🩴", difficulty: "easy", decoy_en: "Flip-flops", decoy_ar: "شبشب" },
      { word_en: "Earrings", word_ar: "أقراط", emoji: "👂", difficulty: "easy", decoy_en: "Studs", decoy_ar: "فصوص" },
      { word_en: "Bracelet", word_ar: "سوار", emoji: "📿", difficulty: "easy", decoy_en: "Bangle", decoy_ar: "خلخال" },
      { word_en: "Bowtie", word_ar: "ربطة عنق فراشة", emoji: "🎀", difficulty: "medium", decoy_en: "Cravat", decoy_ar: "كرافت" },
      { word_en: "Suspenders", word_ar: "حمالات", emoji: "👔", difficulty: "hard", decoy_en: "Braces", decoy_ar: "أقواس" },
      { word_en: "Cufflinks", word_ar: "أزرار أكمام", emoji: "👔", difficulty: "hard", decoy_ar: "كفرلاينز", decoy_en: "Links" },
      { word_en: "Leather Jacket", word_ar: "جاكيت جلد", emoji: "🧥", difficulty: "medium", decoy_en: "Biker Jacket", decoy_ar: "جاكيت بايكر" },
      { word_en: "Hoodie", word_ar: "هودي", emoji: "🧥", difficulty: "easy", decoy_en: "Sweatshirt", decoy_ar: "سويت شيرت" },
      { word_en: "Beret", word_ar: "بيريه", emoji: "👒", difficulty: "hard", decoy_en: "Painter's Hat", decoy_ar: "قبعة فنان" },
      { word_en: "Uniform", word_ar: "زي موحد", emoji: "👮", difficulty: "medium", decoy_en: "Costume", decoy_ar: "زي تنكري" },
      { word_en: "Mannequin", word_ar: "مانيكان", emoji: "👤", difficulty: "hard", decoy_en: "Dummy", decoy_ar: "تمثال" },
      { word_en: "Catwalk", word_ar: "ممشى عرض الأزياء", emoji: "👠", difficulty: "hard", decoy_en: "Runway", decoy_ar: "ران واي" }
    ],
    household: [
      { word_en: "Refrigerator", word_ar: "ثلاجة", emoji: "🧊", difficulty: "easy", decoy_en: "Freezer", decoy_ar: "فريزر" },
      { word_en: "Microwave", word_ar: "ميكروويف", emoji: "🍲", difficulty: "easy", decoy_en: "Oven", decoy_ar: "فرن" },
      { word_en: "Washing Machine", word_ar: "غسالة", emoji: "🧺", difficulty: "easy", decoy_en: "Dryer", decoy_ar: "مجفف" },
      { word_en: "Vacuum Cleaner", word_ar: "مكنسة كهربائية", emoji: "🧹", difficulty: "easy", decoy_en: "Broom", decoy_ar: "مقشة" },
      { word_en: "Toaster", word_ar: "محمصة خبز", emoji: "🍞", difficulty: "easy", decoy_en: "Grill", decoy_ar: "شواية" },
      { word_en: "Coffee Maker", word_ar: "آلة صنع القهوة", emoji: "☕", difficulty: "easy", decoy_en: "Kettle", decoy_ar: "غلاية" },
      { word_en: "Television", word_ar: "تلفزيون", emoji: "📺", difficulty: "easy", decoy_en: "Monitor", decoy_ar: "شاشة" },
      { word_en: "Sofa", word_ar: "أريكة", emoji: "🛋️", difficulty: "easy", decoy_en: "Armchair", decoy_ar: "كرسي مريح" },
      { word_en: "Bed", word_ar: "سرير", emoji: "🛏️", difficulty: "easy", decoy_en: "Mattress", decoy_ar: "مرتبة" },
      { word_en: "Table", word_ar: "طاولة", emoji: "🪑", difficulty: "easy", decoy_en: "Desk", decoy_ar: "مكتب" },
      { word_en: "Chair", word_ar: "كرسي", emoji: "🪑", difficulty: "easy", decoy_en: "Stool", decoy_ar: "مقعد" },
      { word_en: "Mirror", word_ar: "مرآة", emoji: "🪞", difficulty: "easy", decoy_en: "Glass", decoy_ar: "زجاج" },
      { word_en: "Wardrobe", word_ar: "خزانة ملابس", emoji: "🧥", difficulty: "medium", decoy_en: "Closet", decoy_ar: "دولاب" },
      { word_en: "Bathtub", word_ar: "حوض استحمام", emoji: "🛁", difficulty: "easy", decoy_en: "Shower", decoy_ar: "دش" },
      { word_en: "Curtains", word_ar: "ستائر", emoji: "🪟", difficulty: "easy", decoy_en: "Blinds", decoy_ar: "شيش" },
      { word_en: "Lamp", word_ar: "مصباح", emoji: "💡", difficulty: "easy", decoy_en: "Lantern", decoy_ar: "فانوس" },
      { word_en: "Pillow", word_ar: "وسادة", emoji: "🛌", difficulty: "easy", decoy_en: "Cushion", decoy_ar: "خدادية" },
      { word_en: "Blanket", word_ar: "بطانية", emoji: "🛌", difficulty: "easy", decoy_en: "Quilt", decoy_ar: "لحاف" },
      { word_en: "Towel", word_ar: "منشفة", emoji: "🚿", difficulty: "easy", decoy_en: "Bathmat", decoy_ar: "سجادة حمام" },
      { word_en: "Candle", word_ar: "شمعة", emoji: "🕯️", difficulty: "easy", decoy_en: "Incense", decoy_ar: "بخور" },
      { word_en: "Toothbrush", word_ar: "فرشاة أسنان", emoji: "🪥", difficulty: "easy", decoy_en: "Floss", decoy_ar: "خيط أسنان" },
      { word_en: "Hammer", word_ar: "مطرقة", emoji: "🔨", difficulty: "easy", decoy_en: "Mallet", decoy_ar: "مقرعة" },
      { word_en: "Screwdriver", word_ar: "مفك", emoji: "🪛", difficulty: "medium", decoy_en: "Wrench", decoy_ar: "مفتاح ربط" },
      { word_en: "Broom", word_ar: "مقشة", emoji: "🧹", difficulty: "easy", decoy_en: "Mop", decoy_ar: "ممسحة" },
      { word_en: "Iron", word_ar: "مكواة", emoji: "💨", difficulty: "easy", decoy_en: "Steamer", decoy_ar: "جهاز بخار" },
      { word_en: "Fan", word_ar: "مروحة", emoji: "🌀", difficulty: "easy", decoy_en: "Air Conditioner", decoy_ar: "تكييف" },
      { word_en: "Clock", word_ar: "ساعة", emoji: "⏰", difficulty: "easy", decoy_en: "Timer", decoy_ar: "مؤقت" },
      { word_en: "Key", word_ar: "مفتاح", emoji: "🔑", difficulty: "easy", decoy_en: "Lock", decoy_ar: "قفل" },
      { word_en: "Scissors", word_ar: "مقص", emoji: "✂️", difficulty: "easy", decoy_en: "Shears", decoy_ar: "مقص تقليم" },
      { word_en: "Ladder", word_ar: "سلم", emoji: "🪜", difficulty: "medium", decoy_en: "Stairs", decoy_ar: "درج" },
      { word_en: "Bin", word_ar: "سلة مهملات", emoji: "🗑️", difficulty: "easy", decoy_en: "Dumpster", decoy_ar: "حاوية" },
      { word_en: "Vase", word_ar: "مزهرية", emoji: "🏺", difficulty: "medium", decoy_en: "Pot", decoy_ar: "وعاء" },
      { word_en: "Hanger", word_ar: "شماعة", emoji: "👗", difficulty: "easy", decoy_en: "Hook", decoy_ar: "خطاف" },
      { word_en: "Shelf", word_ar: "رف", emoji: "📚", difficulty: "easy", decoy_en: "Rack", decoy_ar: "حامل" },
      { word_en: "Dishwasher", word_ar: "غسالة أطباق", emoji: "🍽️", difficulty: "medium", decoy_en: "Sink", decoy_ar: "حوض" },
      { word_en: "Blender", word_ar: "خلاط", emoji: "🍹", difficulty: "medium", decoy_en: "Mixer", decoy_ar: "مضرب" },
      { word_en: "Radiator", word_ar: "رادياتير", emoji: "🔥", difficulty: "hard", decoy_en: "Heater", decoy_ar: "سخان" },
      { word_en: "Soap", word_ar: "صابون", emoji: "🧼", difficulty: "easy", decoy_en: "Detergent", decoy_ar: "منظف" },
      { word_en: "Sponge", word_ar: "إسفنجة", emoji: "🧽", difficulty: "easy", decoy_en: "Cloth", decoy_ar: "خرقة" },
      { word_en: "Matches", word_ar: "كبريت", emoji: "🔥", difficulty: "easy", decoy_en: "Lighter", decoy_ar: "ولاعة" }
    ],
    space: [
      { word_en: "Astronaut", word_ar: "رائد فضاء", emoji: "👩‍🚀", difficulty: "easy", decoy_en: "Pilot", decoy_ar: "طيار" },
      { word_en: "The Moon", word_ar: "القمر", emoji: "🌙", difficulty: "easy", decoy_en: "Asteroid", decoy_ar: "كويكب" },
      { word_en: "The Sun", word_ar: "الشمس", emoji: "☀️", difficulty: "easy", decoy_en: "Star", decoy_ar: "نجم" },
      { word_en: "Galaxy", word_ar: "مجرة", emoji: "🌌", difficulty: "medium", decoy_en: "Nebula", decoy_ar: "سديم" },
      { word_en: "Black Hole", word_ar: "ثقب أسود", emoji: "🕳️", difficulty: "medium", decoy_en: "Void", decoy_ar: "فراغ" },
      { word_en: "Planet", word_ar: "كوكب", emoji: "🪐", difficulty: "easy", decoy_en: "Satellite", decoy_ar: "قمر صناعي" },
      { word_en: "Alien", word_ar: "فضائي", emoji: "👽", difficulty: "easy", decoy_en: "Monster", decoy_ar: "وحش" },
      { word_en: "Rocket", word_ar: "صاروخ", emoji: "🚀", difficulty: "easy", decoy_en: "Missile", decoy_ar: "صاروخ موجه" },
      { word_en: "Mars", word_ar: "المريخ", emoji: "🔴", difficulty: "medium", decoy_en: "Venus", decoy_ar: "الزهرة" },
      { word_en: "Saturn", word_ar: "زحل", emoji: "🪐", difficulty: "medium", decoy_en: "Jupiter", decoy_ar: "المشتري" },
      { word_en: "Telescope", word_ar: "تلسكوب", emoji: "🔭", difficulty: "medium", decoy_en: "Binoculars", decoy_ar: "منظار" },
      { word_en: "Gravity", word_ar: "جاذبية", emoji: "🍏", difficulty: "hard", decoy_en: "Magnetism", decoy_ar: "مغناطيسية" },
      { word_en: "Orbit", word_ar: "مدار", emoji: "🔄", difficulty: "hard", decoy_en: "Cycle", decoy_ar: "دورة" },
      { word_en: "Comet", word_ar: "مذنب", emoji: "☄️", difficulty: "medium", decoy_en: "Meteor", decoy_ar: "شهاب" },
      { word_en: "Milky Way", word_ar: "درب التبانة", emoji: "🌌", difficulty: "medium", decoy_en: "Universe", decoy_ar: "الكون" },
      { word_en: "Spacesuit", word_ar: "بدلة فضاء", emoji: "👨‍🚀", difficulty: "medium", decoy_en: "Diving Suit", decoy_ar: "بدلة غوص" },
      { word_en: "Cosmos", word_ar: "الفضاء الخارجي", emoji: "🚀", difficulty: "hard", decoy_en: "Infinity", decoy_ar: "لانهاية" },
      { word_en: "Atmosphere", word_ar: "غلاف جوي", emoji: "☁️", difficulty: "hard", decoy_en: "Ozone", decoy_ar: "أوزون" },
      { word_en: "Supernova", word_ar: "مستعر أعظم", emoji: "💥", difficulty: "hard", decoy_en: "Explosion", decoy_ar: "انفجار" },
      { word_en: "UFO", word_ar: "طبق طائر", emoji: "🛸", difficulty: "medium", decoy_en: "Saucer", decoy_ar: "صحن" },
      { word_en: "Space Station", word_ar: "محطة فضاء", emoji: "🛰️", difficulty: "hard", decoy_en: "Base", decoy_ar: "قاعدة" },
      { word_en: "Big Bang", word_ar: "الانفجار العظيم", emoji: "🎇", difficulty: "hard", decoy_en: "Ignition", decoy_ar: "إشعال" },
      { word_en: "Light Year", word_ar: "سنة ضوئية", emoji: "✨", difficulty: "hard", decoy_en: "Distance", decoy_ar: "مسافة" },
      { word_en: "Constellation", word_ar: "كوكبة", emoji: "✨", difficulty: "hard", decoy_en: "Pattern", decoy_ar: "نمط" },
      { word_en: "Jupiter", word_ar: "المشتري", emoji: "🟠", difficulty: "medium", decoy_en: "Saturn", decoy_ar: "زحل" },
      { word_en: "Pluto", word_ar: "بلوتو", emoji: "🌑", difficulty: "medium", decoy_en: "Dwarf Planet", decoy_ar: "كوكب قزم" },
      { word_en: "Solar System", word_ar: "المجموعة الشمسية", emoji: "☀️", difficulty: "medium", decoy_en: "Galactic System", decoy_ar: "نظام مجري" },
      { word_en: "Wormhole", word_ar: "ثقب دودي", emoji: "🌀", difficulty: "hard", decoy_en: "Portal", decoy_ar: "بوابة" },
      { word_en: "Asteroid", word_ar: "كويكب", emoji: "🪨", difficulty: "medium", decoy_en: "Rock", decoy_ar: "صخرة" },
      { word_en: "Lunar Module", word_ar: "مركبة هبوط قمري", emoji: "🌑", difficulty: "hard", decoy_en: "Lander", decoy_ar: "هابط" },
      { word_en: "Rover", word_ar: "مسبار", emoji: "🚜", difficulty: "medium", decoy_en: "Drone", decoy_ar: "درون" },
      { word_en: "Vacuum", word_ar: "فراغ", emoji: "🕳️", difficulty: "hard", decoy_en: "Empty Space", decoy_ar: "مساحة فارغة" },
      { word_en: "Eclipse", word_ar: "خسوف", emoji: "🌙", difficulty: "hard", decoy_en: "Shadow", decoy_ar: "ظل" },
      { word_en: "Sky", word_ar: "سماء", emoji: "☁️", difficulty: "easy", decoy_en: "Firmament", decoy_ar: "جلد" },
      { word_en: "Starfield", word_ar: "حقل نجوم", emoji: "✨", difficulty: "hard", decoy_en: "Canvas", decoy_ar: "لوحة" },
      { word_en: "Nebula", word_ar: "سديم", emoji: "☁️", difficulty: "hard", decoy_en: "Cloud", decoy_ar: "سحابة" },
      { word_en: "Quasar", word_ar: "كوازار", emoji: "🔦", difficulty: "hard", decoy_en: "Beacon", decoy_ar: "منارة" },
      { word_en: "Satellite Dish", word_ar: "دش استقبال", emoji: "📡", difficulty: "medium", decoy_en: "Antenna", decoy_ar: "أنتينا" },
      { word_en: "Meteorite", word_ar: "نيزك", emoji: "🪨", difficulty: "medium", decoy_en: "Stone", decoy_ar: "حجر" },
      { word_en: "Universe", word_ar: "الكون", emoji: "♾️", difficulty: "medium", decoy_en: "Existence", decoy_ar: "الوجود" }
    ],
    arabic_culture: [
      { word_en: "Camel", word_ar: "جمل", emoji: "🐪", difficulty: "easy", decoy_en: "Dromedary", decoy_ar: "جمل وحيد السنام" },
      { word_en: "Oud", word_ar: "عود", emoji: "🎸", difficulty: "medium", decoy_en: "Lute", decoy_ar: "لوت" },
      { word_en: "Dates", word_ar: "تمر", emoji: "🌴", difficulty: "easy", decoy_en: "Fruit", decoy_ar: "فاكهة" },
      { word_en: "Henna", word_ar: "حناء", emoji: "✋", difficulty: "medium", decoy_en: "Tattoo", decoy_ar: "وشم" },
      { word_en: "Fez", word_ar: "طربوش", emoji: "🎩", difficulty: "hard", decoy_en: "Hat", decoy_ar: "قبعة" },
      { word_en: "Hookah", word_ar: "شيشة", emoji: "💨", difficulty: "medium", decoy_en: "Pipe", decoy_ar: "غليون" },
      { word_en: "Bazaar", word_ar: "سوق", emoji: "🏪", difficulty: "easy", decoy_en: "Market", decoy_ar: "سوبر ماركت" },
      { word_en: "Falcon", word_ar: "صقر", emoji: "🦅", difficulty: "medium", decoy_en: "Hawk", decoy_ar: "حداأة" },
      { word_en: "Hummus", word_ar: "حمص", emoji: "🧆", difficulty: "easy", decoy_en: "Dip", decoy_ar: "غموس" },
      { word_en: "Baklava", word_ar: "بقلاوة", emoji: "🍰", difficulty: "medium", decoy_en: "Pastry", decoy_ar: "معجنات" },
      { word_en: "Mosaic", word_ar: "فسيفساء", emoji: "🧱", difficulty: "hard", decoy_en: "Tile", decoy_ar: "بلاط" },
      { word_en: "Shawarma", word_ar: "شاورما", emoji: "🌯", difficulty: "easy", decoy_en: "Kebab", decoy_ar: "كباب" },
      { word_en: "Incense", word_ar: "بخور", emoji: "💨", difficulty: "medium", decoy_en: "Scent", decoy_ar: "رائحة" },
      { word_en: "Lantern", word_ar: "فانوس", emoji: "🪔", difficulty: "easy", decoy_en: "Lamp", decoy_ar: "مصباح" },
      { word_en: "Coffee", word_ar: "قهوة عربية", emoji: "☕", difficulty: "easy", decoy_en: "Tea", decoy_ar: "شاي" },
      { word_en: "Tent", word_ar: "خيمة", emoji: "⛺", difficulty: "easy", decoy_en: "Camp", decoy_ar: "معسكر" },
      { word_en: "Sandals", word_ar: "نعال", emoji: "🩴", difficulty: "easy", decoy_en: "Shoes", decoy_ar: "أحذية" },
      { word_en: "Couscous", word_ar: "كسكسي", emoji: "🥣", difficulty: "medium", decoy_en: "Grain", decoy_ar: "حبوب" },
      { word_en: "Prayer Mat", word_ar: "سجادة صلاة", emoji: "🛐", difficulty: "medium", decoy_en: "Rug", decoy_ar: "سجادة" },
      { word_en: "Desert Oasis", word_ar: "واحة", emoji: "🌴", difficulty: "medium", decoy_en: "Garden", decoy_ar: "حديقة" },
      { word_en: "Palm Tree", word_ar: "نخلة", emoji: "🌴", difficulty: "easy", decoy_en: "Tree", decoy_ar: "شجرة" },
      { word_en: "Arabian Horse", word_ar: "حصان عربي", emoji: "🐎", difficulty: "medium", decoy_en: "Pony", decoy_ar: "مهرة" },
      { word_en: "Calligraphy", word_ar: "خط عربي", emoji: "🖋️", difficulty: "hard", decoy_en: "Writing", decoy_ar: "كتابة" },
      { word_en: "Spices", word_ar: "بهارات", emoji: "🌶️", difficulty: "medium", decoy_en: "Herbs", decoy_ar: "أعشاب" },
      { word_en: "Abaya", word_ar: "عباءة", emoji: "👘", difficulty: "medium", decoy_en: "Robe", decoy_ar: "رداء" },
      { word_en: "Mint Tea", word_ar: "شاي بالنعناع", emoji: "🍵", difficulty: "easy", decoy_en: "Juice", decoy_ar: "عصير" },
      { word_en: "Fiddle", word_ar: "ربابة", emoji: "🎻", difficulty: "hard", decoy_en: "Violin", decoy_ar: "كمان" },
      { word_en: "Carpet", word_ar: "سجاد", emoji: "🧶", difficulty: "medium", decoy_en: "Mat", decoy_ar: "حصير" },
      { word_en: "Silverware", word_ar: "فضيات", emoji: "🍴", difficulty: "hard", decoy_en: "Plates", decoy_ar: "أطباق" },
      { word_en: "Tabbouleh", word_ar: "تبولة", emoji: "🥗", difficulty: "medium", decoy_en: "Salad", decoy_ar: "سلطة" },
      { word_en: "Olive tree", word_ar: "شجرة زيتون", emoji: "🫒", difficulty: "medium", decoy_en: "Fig tree", decoy_ar: "شجرة تين" },
      { word_en: "Kaftan", word_ar: "قفطان", emoji: "🥋", difficulty: "hard", decoy_en: "Dress", decoy_ar: "فستان" },
      { word_en: "Turmeric", word_ar: "كركم", emoji: "🟡", difficulty: "hard", decoy_en: "Saffron", decoy_ar: "زعفران" },
      { word_en: "Minaret", word_ar: "مئذنة", emoji: "🕌", difficulty: "hard", decoy_en: "Tower", decoy_ar: "برج" },
      { word_en: "Dinar", word_ar: "دينار", emoji: "💵", difficulty: "medium", decoy_en: "Money", decoy_ar: "نقود" },
      { word_en: "Falafel", word_ar: "فلافل", emoji: "🧆", difficulty: "easy", decoy_en: "Burger", decoy_ar: "برجر" },
      { word_en: "Ma'amoul", word_ar: "معمول", emoji: "🍪", difficulty: "medium", decoy_en: "Cookie", decoy_ar: "كوكيز" },
      { word_en: "Mansaf", word_ar: "منسف", emoji: "🍚", difficulty: "hard", decoy_en: "Paella", decoy_ar: "باييلا" },
      { word_en: "Saffron", word_ar: "زعفران", emoji: "🌸", difficulty: "hard", decoy_en: "Spice", decoy_ar: "توابل" },
      { word_en: "Thobe", word_ar: "ثوب", emoji: "👔", difficulty: "medium", decoy_en: "Gown", decoy_ar: "ثوب نوم" }
    ]
  };

  /**
   * HELPERS Implementation (window.SpyGameCore.state)
   */
  const helpers = {
    generateRoomCode: () => Math.random().toString(36).substring(2, 8).toUpperCase(),
    shuffle: (array) => {
      const newArr = [...array];
      for (let i = newArr.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [newArr[i], newArr[j]] = [newArr[j], newArr[i]];
      }
      return newArr;
    },
    pickRandom: (array) => array[Math.floor(Math.random() * array.length)],
    pickByDifficulty: (arr, diff) => {
      const filtered = arr.filter(item => item.difficulty === diff);
      return filtered.length ? helpers.pickRandom(filtered) : helpers.pickRandom(arr);
    },
    checkFuzzyMatch: (a, b) => {
      const s1 = a.toLowerCase().trim().replace(/\s+/g, '');
      const s2 = b.toLowerCase().trim().replace(/\s+/g, '');
      if (s1 === s2) return true;
      if (Math.abs(s1.length - s2.length) > 1) return false;
      let i = 0, j = 0, diffs = 0;
      while (i < s1.length && j < s2.length) {
        if (s1[i] !== s2[j]) {
          diffs++;
          if (diffs > 1) return false;
          if (s1.length > s2.length) i++;
          else if (s1.length < s2.length) j++;
          else { i++; j++; }
        } else { i++; j++; }
      }
      return diffs + (s1.length - i) + (s2.length - j) <= 1;
    },
    formatTime: (sec) => `${Math.floor(sec / 60)}:${(sec % 60).toString().padStart(2, '0')}`,
    generateId: () => Array.from({length: 12}, () => Math.floor(Math.random() * 16).toString(16)).join(''),
    t: (key) => {
        const lang = localStorage.getItem("spy_lang") || "en";
        return I18N[lang][key] || key;
    },
    currentLang: () => localStorage.getItem("spy_lang") || "en",
    setLang: (lang) => {
      localStorage.setItem("spy_lang", lang);
      location.reload(); // Re-renders app
    },
    soundEnabled: () => localStorage.getItem("spy_sound") !== "false",
    setSoundEnabled: (bool) => localStorage.setItem("spy_sound", bool)
  };

  // Expose to Global Bus
  window.SpyGameCore.state = {
    GAME_CONFIG,
    CSS_VARS: {
      'spy-bg-deep': '#080C18',
      'spy-bg-mid': '#0F1626',
      'spy-card': 'rgba(255,255,255,0.04)',
      'spy-border': 'rgba(255,255,255,0.08)',
      'spy-gold': '#F5A623',
      'spy-teal': '#00D4AA',
      'spy-danger': '#FF4D6D',
      'spy-purple': '#9B6DFF',
      'spy-text': '#F0F4FF',
      'spy-muted': '#6B7A99'
    },
    I18N,
    WORD_BANK,
    ...helpers
  };

  // Inject CSS Variables on load
  const style = document.createElement('style');
  style.id = "spy-game-vars";
  style.textContent = `:root {
    ${Object.entries(window.SpyGameCore.state.CSS_VARS).map(([k, v]) => `--${k}:${v};`).join('\n')}
    --spy-glow-gold: 0 0 20px rgba(245,166,35,0.3);
    --spy-glow-teal: 0 0 20px rgba(0,212,170,0.3);
    --spy-glow-danger: 0 0 20px rgba(255,77,109,0.3);
    --spy-vh: 1vh;
  }`;
  document.head.appendChild(style);

  console.log("SpyGameCore: Config Loaded (600 Words)");

})();